---
username: "{{ username_sec }}"

# Used in Geerlingguy.ntp
ntp_servers:
  - 0.dk.pool.ntp.org
  - 1.dk.pool.ntp.org
  - 2.dk.pool.ntp.org
  - 3.dk.pool.ntp.org

timezone: Europe/Copenhagen
ntp_tinker_panic: true
ntp_manage_config: true
ntp_timezone: "{{ timezone }}"

# Used in geerlingguy.security
security_sudoers_passwordless: [ "{{ username_sec }}" ]
security_fail2ban_enabled: false

# Used in geerlingguy.pip
pip_package: python3-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
pip_install_packages:
      - name: docker
      - name: docker-compose

# Used in geerlingguy.docker
docker_daemon_options: {"iptables": true}
docker_users:
  - "{{ username_sec }}"

extra_packages: 
  - curl
  - git
  - nano
  - python3
  - python3-pip

extra_packages_nettools: []

enable_os_update: false
enable_extra_packages: false
enable_extra_packages_nettools: false
enable_cockpit: false
enable_auditd: false
enable_rkhunter: false
enable_lynis: false
enable_os_hardening: false

