---
# Used in Geerlingguy.ntp
ntp_servers:
  - 0.dk.pool.ntp.org
  - 1.dk.pool.ntp.org
  - 2.dk.pool.ntp.org
  - 3.dk.pool.ntp.org

timezone: Europe/Copenhagen
ntp_tinker_panic: true
ntp_manage_config: true
ntp_timezone: "{{ timezone }}"

# Used in geerlingguy.security
security_sudoers_passwordless: [ 'deploy' ]
security_fail2ban_enabled: false

# Used in geerlingguy.pip
pip_package: python3-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
pip_install_packages:
      - name: docker
      - name: docker-compose

# Used in geerlingguy.docker
docker_daemon_options: {"iptables": true}
docker_users: [ 'deploy' ]
  
extra_packages: 
  - curl
  - git
  - nano
  - micro
  - python3
  - python3-pip

extra_packages_nettools: 
  - dnsutils
  - net-tools
  - nmap
  - netcat

enable_os_update: true
