---
- name: Localhost playbooks inventory to sshconfig
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Add Ansible inventory mappings to ~/.ssh/config
      ansible.builtin.blockinfile:
        path: /home/rolf/.ssh/config
        block: |
            {% for host in groups['prod-servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['test-servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['windows'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
