---
- hosts: localhost
  gather_facts: true
  become: true
  tasks: 
  - name: Add Ansible inventory mappings to ~/.ssh/config
    blockinfile:
      path: /home/rolf/.ssh/config
      block: |
        {% for host in groups['servers'] %}
        host {{ hostvars[host].inventory_hostname_short }} {{ host }} 
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
        {% for host in groups['test'] %}
        host {{ hostvars[host].inventory_hostname_short }} {{ host }} 
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
        {% for host in groups['windows'] %}
        host {{ hostvars[host].inventory_hostname_short }} {{ host }} 
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}

        {% for host in groups['docker'] %}
        host {{ hostvars[host].inventory_hostname_short }} {{ host }} 
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}


