---
- hosts: localhost
  tasks: 
  - name: Add Ansible inventory mappings to /etc/hosts
    become: true
    blockinfile:
      path: /home/rolf/.ssh/config
      block: |
        {% for host in groups['all'] %}
        host {{ hostvars[host].inventory_hostname_short }}
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
