---
- hosts: localhost
  tasks: 
  - name: Add Ansible inventory mappings to /etc/hosts
    become: true
    blockinfile:
      path: /etc/hosts
      block: |
        {% for host in groups['servers'] %}
        {{ hostvars[host].ansible_host }}   {{ host }}    {{ hostvars[host].inventory_hostname_short }}
        {% endfor %}
        {% for host in groups['test'] %}
        {{ hostvars[host].ansible_host }}   {{ host }}    {{ hostvars[host].inventory_hostname_short }}
        {% endfor %}
        {% for host in groups['windows'] %}
        {{ hostvars[host].ansible_host }}   {{ host }}    {{ hostvars[host].inventory_hostname_short }}
        {% endfor %}
        {% for host in groups['docker'] %}
        {{ hostvars[host].ansible_host }}   {{ host }}    {{ hostvars[host].inventory_hostname_short }}
        {% endfor %}
        
