---
- hosts: localhost
  tasks: 
  - name: Add Ansible inventory mappings to /etc/hosts
    become: true
    blockinfile:
      path: /home/rolf/.ssh/config
      block: |
        {% for host in groups['servers'] %}
        host {{ hostvars[host].inventory_hostname_short }}
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
        {% for host in groups['test'] %}
        host {{ hostvars[host].inventory_hostname_short }}
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
        {% for host in groups['windows'] %}
        host {{ hostvars[host].inventory_hostname_short }}
            HostName {{ hostvars[host].ansible_host }} 
            User deploy
            Port 22
            IdentityFile ~/.ssh/deploy
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}
        {% for host in groups['kali'] %}
        host kali
            HostName 127.0.0.1 
            User vagrant
            Port 2208
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        
        {% endfor %}