services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      - PRIMARY=https://pi1.lan|{{ pihole_password}}
      - REPLICAS=https://pi2.lan|{{ pihole_password}}
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - FULL_SYNC=false
      - RUN_GRAVITY=false
      - TZ=Europe/Copenhagen
      - SYNC_CONFIG_DNS=true
      - SYNC_CONFIG_RESOLVER=true
      - SYNC_CONFIG_DATABASE=true
      - SYNC_CONFIG_MISC=true
      - SYNC_GRAVITY_AD_LIST=true
      - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
      - SYNC_GRAVITY_DOMAIN_LIST=true
      - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
      - SYNC_GRAVITY_CLIENT=true
      - SYNC_GRAVITY_CLIENT_BY_GROUP=true
      - CRON=*/10 * * * *
