firewall_disable_ufw: false

firewall_allowed_tcp_ports:
  - "22"
  - "53"    # pi-hole
  - "80"    # Local http
  - "443"   # local https
  - "9001"  # Portainer in docker exposed on localhost
  - "9443"  # Portainer in docker exposed on localhost
  - "9090"  # Cockpit
  - "8001"  # Homer in Docker
  - "6060"  # Crowdsec
  - "8080"  # Crowdsec 

firewall_allowed_udp_ports:
  - "53"    # pi-hole
  - "51820" # Wireguard

docker_dir: /opt/docker/data

# Packages
extra_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - nano
  - htop
  - unzip
  - git
  - python3
  - python3-pip
  - nmap
  - dnsutils
  - net-tools
  - rsync
  - netcat
  - cockpit

# Enable/disable functionality
enable_pihole: true
host: ''
