enable_ufw: true
enable_crowdsec: false
enable_portainer: true
enable_watchtower: false
enable_pihole: true
enable_wireguard: false
enable_cockpit: true

extra_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - nano
  - htop
  - unzip
  - git
  - python3
  - python3-pip
  - nmap
  - dnsutils
  - net-tools
  - rsync
  - netcat
