enable_ufw: true
enable_crowdsec: true
enable_portainer: true
enable_watchtower: false
enable_cokpit: true
enable_pihole: false
enable_wireguard: false

extra_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - nano
  - htop
  - unzip
  - git
  - python3
  - python3-pip
  - nmap
  - dnsutils
  - net-tools
  - rsync
  - netcat
  - cockpit