# Used in geerlingguy.security
security_sudoers_passwordless:
  - labadmin
  - deploy
  - pi

# Used in geerlingguy.firewall
firewall_state: stopped
firewall_enabled_at_boot: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# Used in geerlingguy.ntp
ntp_timezone: Europe/Copenhagen

pip_install_packages:
      - name: docker
      - name: docker-compose

docker_users:
  - labadmin
  - deploy
  - pi