---
enable_crowdsec: true
crowdsec_install_firewall_bouncer: true
crowdsec_multi_server: true
crowdsec_lapi_server: true
crowdsec_lapi_ip: 192.168.56.11
crowdsec_agent_hosts: 
  - srv02.test
  - srv03.test
  - srv04.test
crowdsec_agent_hosts_password: 'VeryLongPasswordShouldBeRandomChangeme2022!'
crowdsec_psql_db_user: crowdsec
crowdsec_psql_db_password: 'VeryLongPasswordPsqlChangeme2022!'
crowdsec_psql_db_name: crowdsec

# Packages
extra_packages: 
  - curl
  - nano
  

