---
- name: Make sure the Portainer container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "portainer/portainer-ce"
    pull: yes
    state: 'started'
    ports:
        - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
    restart_policy: unless-stopped
