---
- name: Container is created and running {{ container_name }}
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "jokobsk/pi.alert:latest"
    pull: true
    state: 'started'
    network_mode: "host"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/pialert_db:/home/pi/pialert/db"
      - "{{ docker_dir }}/{{ container_name }}/pialert_config:/home/pi/pialert/config"
      - "{{ docker_dir }}/{{ container_name }}/pialert_logs:/home/pi/pialert/front/log"
    env:
      TZ: "{{ timezone }}"
      HOST_USER_ID: 1000
      HOST_USER_GID: 1000
      PORT: 20211
    restart_policy: unless-stopped
