---
test_servers:
  hosts:
    srv01.test:
      ansible_host: 192.168.56.21
    srv02.test:
      ansible_host: 192.168.56.22
  vars:
    ansible_user: deploy
    remote_user: deploy
    ansible_ssh_private_key_file: '~/.ssh/deploy'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ControlMaster: auto
    ControlPersist: 60s
    vault_password_file: ~/.vault_pass
