---
- name: Provision a new server on test og lab
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:
    - role: system
      tags: system

  tasks:
    - name: Install package ufw
      tags: ufw
      ansible.builtin.package:
        state: present
        name: ufw
      notify:
        - Reload ufw

    - name: Set logging
      community.general.ufw:
        logging: 'on'

    - name: Allow necessary ports in UFW
      community.general.ufw:
        rule: allow
        direction: 'in'
        from_ip: 'any'
        to_ip: 'any'
        port: 22
        proto: 'tcp'
        comment: "Allow ssh from any"

    - name: Enable Firewall ufw
      community.general.ufw:
        state: enabled

- name: Provision a new Desktop Server
  hosts: ubt.test
  gather_facts: true
  become: true

  tasks:
    - name: Install Desktop
      ansible.builtin.package:
        name: ubuntu-desktop-minimal
        state: present
    - name: Reboot systems
      ansible.builtin.reboot:
