---
#
# Tasks and roles for all hosts
#

- name: Run on all PROD_SERVERS
  hosts: prod_servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false

  roles:

    - role: system
      tags:
        - users
        - defaults

    - role: geerlingguy.security
      tags:
        - security
        - defaults

    - role: geerlingguy.ntp
      tags:
        - ntp
        - defaults

    - role: ufw
      tags:
        - firewall
        - ufw

# #### NAS.LAN ####
# - name: Run on nas.lan
#   hosts: nas.lan
#   gather_facts: true
#   become: true
#   vars_files: group_vars/secrets.yml
#   roles:
#     - role: nfs_server
#       tags:
#         - nfs-server

# #### PI1.LAN ####
# - name: Run on "pi1.lan"
#   hosts: pi1.lan
#   gather_facts: true
#   become: true

#   vars_files:
#     - group_vars/secrets.yml

# #### PI2.LAN ####
# - name: Run on "pi2.lan"
#   hosts: pi2.lan
#   gather_facts: true
#   become: true

#   vars_files:
#     - group_vars/secrets.yml

# #### DOCKER01.LAN ####
# - name: Run on "docker01.lan"
#   hosts: docker01.lan
#   # gather_facts: true
#   become: true

#   vars_files:
#     - group_vars/secrets.yml

#   roles:

#     - role: nfsclient
#       tags:
#         - containers
#         - nfsclient

#     - role: geerlingguy.pip
#       tags:
#         - containers

#     - role: geerlingguy.docker
#       tags:
#         - containers

#     - role: portainer
#       tags:
#         - containers
#         - portainer

#     - role: watchtower
#       tags:
#         - containers
#         - watchtower

#     - role: uptimekuma
#       tags:
#         - containers
#         - uptimekuma


#     - role: littlelink
#       tags:
#         - containers
#         - littlelink
