---

- name: Run on all PROD_SERVERS
  hosts: pve.lan:pve1.lan
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:
    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false
