---
#
# Tasks and roles for all hosts
#

- name: Run on all PROD_SERVERS
  hosts: prod_servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false

  roles:

    - role: system
      tags:
        - users
        - defaults

    - role: geerlingguy.security
      tags:
        - security
        - defaults

    - role: geerlingguy.ntp
      tags:
        - ntp
        - defaults

    - role: ufw
      tags:
        - firewall
        - ufw

#### CLOUD01.LAN ####
- name: Run on "cloud01.lan"
  hosts: cloud01.lan
  # gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: geerlingguy.pip
      tags:
        - containers

    - role: geerlingguy.docker
      tags:
        - containers

    - role: littlelink
      tags:
        - containers
        - littlelink
