---
#
# Tasks and roles for all hosts
#

- name: Run on all PROD_SERVERS
  hosts: test_servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false

  roles:

    - role: system
      tags:
        - users
        - defaults

    - role: ufw
      tags:
        - firewall
        - ufw


#### DEV01.LAN ####
- name: Run on "dev01.test"
  hosts: dev01.test
  # gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: geerlingguy.pip
      tags:
        - containers

    - role: geerlingguy.docker
      tags:
        - containers

  tasks:

    - name: Essential-debian | Install extra packages
      ansible.builtin.package:
        name: "{{ extra_packages }}"
        state: present
      tags:
        - wget
        - apt-transport-https
        - install ca-certificates
        - curl
        - nano
        - dnsutils
        - net-tools
        - jq
        - htop
        - git
        - rsync
        - unzip
        - python3
        - python3-pip

    # - name: Install tailscale client
    #   ansible.builtin.shell: 'curl -fsSL https://tailscale.com/install.sh | sh'

