---
- name: Container is created and running {{ container_name }}
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "containrrr/watchtower"
    pull: true
    state: 'started'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ timezone }}"
      WATCHTOWER_SCHEDULE: "15 3 * * 7"
    restart_policy: unless-stopped
