
## Firewall 
open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }
  - { src: any, dest: any, port: '7844', proto: any, direction: out, comment: 'Cloudflaretunnels' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.3.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'Allow from VPN' }

  - { src: any, dest: any, port: '443', proto: udp, direction: out, comment: 'www.intra, amfelt.dk' }

  - { src: any, dest: any, port: '41641', proto: udp, direction: out, comment: 'tailscale' }
  - { src: any, dest: any, port: '3478', proto: udp, direction: out, comment: 'tailscale' }
  - { src: any, dest: any, port: '41641', proto: udp, direction: in, comment: 'tailscale' }
  - { src: any, dest: any, port: '3478', proto: udp, direction: in, comment: 'tailscale' }
