
## Firewall 
open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.30.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # homelab Vlan' }
  - { src: '192.168.3.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'Allow from VPN' }

  - { src: '192.168.10.0/24', dest: any, port: '3000', proto: 'tcp', direction: in, comment: 'HTTP# GIT/forgejo from secure Vlan' }
  - { src: '192.168.31.0/24', dest: any, port: '3000', proto: 'tcp', direction: in, comment: 'HTTP# GIT/forgejo from secure caddy/dmz' }
  - { src: '192.168.10.0/24', dest: any, port: '2222', proto: 'tcp', direction: in, comment: 'SSH 2222# GIT/forgejo from secure Vlan' }
  - { src: '192.168.30.0/24', dest: any, port: '2222', proto: 'tcp', direction: in, comment: 'SSH 2222# GIT/forgejo from homelab Vlan' }
  - { src: '192.168.31.0/24', dest: any, port: '2222', proto: 'tcp', direction: in, comment: 'SSH 2222# GIT/forgejo from secure caddy/dmz' }

## Docker 

nfsclient_local_folder: "/opt/docker"
docker_dir: "{{ nfsclient_local_folder }}/docker_prod"
docker_compose_generator_output_path: "/home/deploy"
docker_compose_generator_uid: "1000"
docker_compose_generator_gid: "1000"
appdata_path: "{{ docker_dir }}"

global_env_vars:
  - "PUID=1000"
  - "PGID=1000"

containers:

  - service_name: forgejo
    active: true
    image: codeberg.org/forgejo/forgejo:9
    ports:
      - '3000:3000'
      - '2222:22'
    volumes:
      - "{{ appdata_path }}/forgejo/data:/data" 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    include_global_env_vars: true
    restart: unless-stopped
