
## Firewall 
open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.30.152', dest: any, port: '443', proto: 'tcp', direction: in, comment: 'HTTPS # From Docker02/Nebula-sync' }
  - { src: '192.168.31.5', dest: any, port: '443', proto: 'tcp', direction: in, comment: 'HTTPS # From caddy proxy' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Allow from Secure Vlan' }
  - { src: '192.168.3.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Allow from VPN' }

  - { src: '192.168.3.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # VPN VLAN' }
  - { src: '192.168.10.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Secure Vlan' }
  - { src: '192.168.20.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Mart Vlan' }
  - { src: '192.168.30.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # HomeLab Vlan' }
  - { src: '192.168.31.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # HomeLab DMZ Vlan' }
  - { src: '192.168.99.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Insecure Vlan' }

#  - { src: any, dest: '192.168.30.101', port: '8080', proto: 'tcp', direction: out, comment: 'http pi sync' }
#  - { src: any, dest: '192.168.30.102', port: '8080', proto: 'tcp', direction: out, comment: 'http pi sync' }

#  - { src: '192.168.30.101', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # pihole 1' }
#  - { src: '192.168.30.102', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # pihole 2' }

#  - { src: '192.168.31.0/24', dest: any, port: '80', proto: 'tcp', direction: in, comment: 'HTTP # Secure Vlan' }
#  - { src: '192.168.31.0/24', dest: any, port: '8080', proto: 'tcp', direction: in, comment: 'HTTP # Secure Vlan' }
#  - { src: '192.168.30.101', dest: any, port: '8080', proto: 'tcp', direction: in, comment: 'HTTP # Secure Vlan' }
#  - { src: '192.168.30.102', dest: any, port: '8080', proto: 'tcp', direction: in, comment: 'HTTP # Secure Vlan' }

