enable_os_update: true
enable_extra_packages: true
enable_extra_packages_nettools: false
enable_cockpit: false
enable_auditd: false
enable_rkhunter: false
enable_lynis: false

## Firewall 
enable_ufw: true
resetufw: true
enable_ufw_deny_out: true

open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'tcp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.10.0/24', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.30.0/24', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # Homelab Vlan' }
  - { src: '192.168.31.0/24', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # HomeLab DMZ' }
  - { src: '192.168.56.0/24', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # KVM / vagrant on localhost' }
  - { src: '192.168.121.0/24', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # KVM / vagrant on localhost' }

  - { src: '192.168.56.0/24', dest: '', port: '80', proto: 'tcp', direction: in, comment: 'http any' } #HTTP
  - { src: '192.168.56.0/24', dest: '', port: '443', proto: 'tcp', direction: in, comment: 'https any' } #HTTPS
  - { src: '192.168.56.0/24', dest: '', port: '9000', proto: 'tcp', direction: in, comment: 'Portainer' } #Portainer
  - { src: '192.168.56.0/24', dest: '', port: '9090', proto: 'tcp', direction: in, comment: 'Cockpit' } #Cockpit
  - { src: '192.168.56.0/24', dest: '', port: '6060', proto: 'tcp', direction: in, comment: 'Crowdsec' } #Crowdsec
  - { src: '192.168.56.0/24', dest: '', port: '6080', proto: 'tcp', direction: in, comment: 'Crowdsec' } #Crowdsec
  - { src: '192.168.56.0/24', dest: '', port: '8080', proto: 'tcp', direction: in, comment: 'Crowdsec' } #Crowdsec
  - { src: '192.168.56.0/24', dest: '', port: '8001', proto: 'tcp', direction: in, comment: 'Littlelink' } #Littlelink
  - { src: '192.168.56.0/24', dest: '', port: '3001', proto: 'tcp', direction: in, comment: 'Uptime-Kuma' } #Uptime-Kuma
  - { src: '192.168.56.0/24', dest: '', port: '5001', proto: 'tcp', direction: in, comment: 'Dockge' } #Dockge

  - { src: any, dest: any, port: '111', proto: any, direction: out, comment: 'NFS' } #NFS
  - { src: any, dest: any, port: '2049', proto: any, direction: out, comment: 'NFS' } #NFS
  - { src: any, dest: any, port: '4045', proto: any, direction: out, comment: 'NFS' } #NFS
  - { src: '192.168.56.0/24', dest: '', port: '111', proto: any, direction: in, comment: 'NFS' } #NFS
  - { src: '192.168.56.0/24', dest: '', port: '2049', proto: any, direction: in, comment: 'NFS' } #NFS
  - { src: '192.168.56.0/24', dest: '', port: '4045', proto: any, direction: in, comment: 'NFS' } #NFS

  - { src: '172.17.0.0/16', dest: '172.17.0.0/16', port: , proto: 'any', direction: out, comment: 'Docker' } #Docker
  - { src: '172.17.0.0/16', dest: '172.17.0.0/16', port: , proto: 'any', direction: in, comment: 'Docker' } #Docker






# Default ports Outgoing
# enable_out_ssh_22: true
# enable_out_dns_53: true
# enable_out_web_80: true
# enable_out_ntp_123: true
# enable_out_web_443: true

# Default ports incomming
# enable_dns53: false
# enable_web80: false
# enable_web443: false

# System ports incomming
# enable_nfs: false
# enable_docker: true
# enable_crowdsec: false
# enable_portainer: false
# enable_littlelink: false
# enable_uptimekuma: false
# enable_watchtower: false
# enable_dockge: false 


# local_lan_ufw:
#   - 192.168.10.0/24   # Vlan secure
#   - 192.168.30.0/24   # Vlan homlab
#   - 192.168.31.0/24   # Vlan secure
#   - fd00::/8          # # Default Lan Ipv6

