
## Firewall 
open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.3.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'Allow from VPN' }

  - { src: '192.168.1.0/24', dest: any, port: '514', proto: 'udp', direction: in, comment: 'syslog udp' }
  - { src: '192.168.10.0/24', dest: any, port: '514', proto: 'udp', direction: in, comment: 'syslog udp' }
  - { src: '192.168.20.0/24', dest: any, port: '514', proto: 'udp', direction: in, comment: 'syslog udp' }
  - { src: '192.168.30.0/24', dest: any, port: '514', proto: 'udp', direction: in, comment: 'syslog udp' }
  - { src: '192.168.31.0/24', dest: any, port: '514', proto: 'udp', direction: in, comment: 'syslog udp' }

  - { src: '192.168.1.0/24', dest: any, port: '514', proto: 'tcp', direction: in, comment: 'syslog tcp' }
  - { src: '192.168.10.0/24', dest: any, port: '514', proto: 'tcp', direction: in, comment: 'syslog tcp' }
  - { src: '192.168.20.0/24', dest: any, port: '514', proto: 'tcp', direction: in, comment: 'syslog tcp' }
  - { src: '192.168.30.0/24', dest: any, port: '514', proto: 'tcp', direction: in, comment: 'syslog tcp' }
  - { src: '192.168.31.0/24', dest: any, port: '514', proto: 'tcp', direction: in, comment: 'syslog tcp' }
