---

- name: Removes subscription nag box
  ansible.builtin.include_tasks:
    file: remove-nag.yml
  when: remove_nag

- name: Remove enterprise repo
  ansible.builtin.include_tasks:
    file: remove-enterprise-repo.yml
  when: remove_enterprise_repo

- name: Add no subcription repo
  ansible.builtin.include_tasks:
    file: add-no-subscription-repo.yml
  when: add_no_subscription_repo
