---

# credit: https://johnscs.com/remove-proxmox51-subscription-notice/ & https://github.com/foundObjects/pve-nag-buster
# edited by Alf149 to fit for PBS

- name: Modify line in file to remove nag message
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
    replace: "false"
    backup: true
  notify: Restart proxmox-backup-proxy
