---
- name: Container is created and running {{ container_name }}
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/techno-tim/littlelink-server:latest"
    pull: true
    state: 'started'
    ports:
      - "8001:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      META_TITLE: 'Rolf Amfelt'
      META_DESCRIPTION: 'Rolf Amfelt Link page'
      META_AUTHOR: 'Rolf Amfelt'
      META_KEYWORDS: 'HomeLab'
      LANG: en
      META_INDEX_STATUS: 'noindex'
      THEME: 'Dark'
      FAVICON_URL: ''
      AVATAR_URL: ''
      AVATAR_2X_URL: ''
      AVATAR_ALT: ''
      NAME: 'Rolf Amfelt'
      BIO: 'Homelab | Almost Nerd'
      BUTTON_ORDER: MASTODON,LINKED_IN,TWITTER,GITHUB,TWITTER

      GITHUB: 'https://github.com/alf149'
      LINKED_IN: 'https://dk.linkedin.com/in/rolf-amfelt-81a43'
      MASTODON: 'https://norrebro.space/@alf194'
      FOOTER: Rolf Amfelt © 2022
    restart_policy: unless-stopped
