---
# Change to https://github.com/Oefenweb/ansible-ufw
- name: Install package ufw
  tags: ufw
  package:
    state: latest
    name: ufw
  notify:
    - restart_ufw
  when:
    - enable_ufw is defined
    - enable_ufw == true

- name: Allow outgoing
  ufw: 
    comment: default allow outgoing
    default: allow
    direction: outgoing
  when:
    - enable_ufw is defined
    - enable_ufw == true
    - enable_ufw_deny_out == false

- name: Deny outgoing
  ufw: 
    comment: default allow outgoing
    default: deny
    direction: outgoing
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out == true
    - enable_ufw == true

- name: Disallow ingoing
  ufw: 
    comment: default deny incoming
    default: deny
    direction: incoming
  when:
    - enable_ufw is defined
    - enable_ufw == true

#reset UFW
- name: Reset UFW
  ufw: 
    logging: on
    state: reset
  notify:
    - restart_ufw
  when:
    - enable_ufw is defined 
    - resetufw is defined
    - enable_ufw == true
    - resetufw == true

# Outgoing roules
# - name: Out allow 22
#   ufw:
#     comment: allow ssh 
#     rule: allow
#     direction: out
#     port: '22'
#     proto: tcp
#   when:
#     - enable_ufw is defined
#     - enable_ufw_deny_out == true
#     - enable_ufw == true

- name: Out allow 53 DNS
  ufw:
    comment: allow ssh 
    rule: allow
    direction: out
    port: '53'
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out == true
    - enable_ufw == true

- name: Out allow 123 NTP
  ufw:
    comment: allow ssh 
    rule: allow
    direction: out
    port: '123'
    proto: udp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out == true
    - enable_ufw == true

- name: Out allow 80 http
  ufw:
    comment: allow ssh 
    rule: allow
    direction: out
    port: '80'
    proto: tcp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out == true
    - enable_ufw == true

- name: Out allow 443 https
  ufw:
    comment: allow ssh 
    rule: allow
    direction: out
    port: '443'
    proto: tcp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out == true
    - enable_ufw == true

# SSH 
- name: Grant ssh access
  ufw:
    comment: allow ssh 
    rule: allow
    direction: in
    port: '22'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_ufw is defined
    - enable_ufw == true

# dns pi-hole
- name: allow 81 pihole (tcp)
  tags: ufw
  ufw:
    comment: allow 81 pihole  (tcp)
    rule: allow
    port: '81'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true
    - enable_ufw == true

- name: allow dns pihole (tcp)
  tags: ufw
  ufw:
    comment: allow dns pihole (tcp)
    rule: allow
    port: '53'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true
    - enable_ufw == true

- name: allow dns pihole (udp)
  tags: ufw
  ufw:
    comment: allow dns pihole (udp)
    rule: allow
    port: '53'
    proto: udp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true 
    - enable_ufw == true

# web server
- name: web server allow http (80)
  tags: ufw
  ufw:
    comment: web server allow http (80)
    rule: allow
    port: '80'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_web80 is defined
    - enable_web80 == true 
    - enable_ufw == true

- name: web server allow https (443)
  tags: ufw
  ufw:
    comment: web server allow https (443)
    rule: allow
    port: '443'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_web443 is defined
    - enable_web443 == true 
    - enable_ufw == true

# Portainer
- name: Portainer (9000)
  tags: ufw
  ufw:
    comment: Portainer (9000)
    rule: allow
    port: '9000'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_portainer is defined
    - enable_portainer == true 
    - enable_ufw == true

# Cockpit
- name: Cockpit (9090)
  tags: ufw
  ufw:
    comment: Cockpit (9001)
    rule: allow
    port: '9090'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_cockpit is defined
    - enable_cockpit == true 
    - enable_ufw == true

# Crowdsec
- name: Crowdsec (6060)
  tags: ufw
  ufw:
    comment: Crowdsec (6060)
    rule: allow
    port: '6060'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true 
    - enable_ufw == true

# Crowdsec
- name: Crowdsec (6080)
  tags: ufw
  ufw:
    comment: Crowdsec (6080)
    rule: allow
    port: '6080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true 
    - enable_ufw == true

# Crowdsec
- name: Crowdsec (8080)
  tags: ufw
  ufw:
    comment: Crowdsec (8080)
    rule: allow
    port: '8080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true 
    - enable_ufw == true

- name: Enable Firewall ufw
  ufw: 
    logging: on
    state: enabled
  notify:
    - restart_ufw
  when:
    - enable_ufw is defined
    - enable_ufw == true

    
