enable_extra_packages: true
extra_packages_nettools: false

## Firewall 
enable_ufw: true
enable_ufw_deny_out: true

open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.30.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }
  - { src: '192.168.3.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # VPN Vlan' }

  - { src: any, dest: any, port: '25', proto: 'tcp', direction: in, comment: 'MAIL' }
  - { src: any, dest: any, port: '465', proto: 'tcp', direction: out, comment: 'MAIL SMTP SSL' }
  - { src: any, dest: any, port: '587', proto: 'tcp', direction: out, comment: 'MAIL SMTP TLS' }

postfix_conf:
  compatibility_level: '3.6'
  inet_protocols: 'ipv4'
  myhostname: 'mail.lan'
  myorigin: '/etc/mailname'
  mydestination:
  mynetworks: '127.0.0.0/8 192.168.1.0/24'
  smtp_generic_maps: 'hash:/etc/postfix/generic'
  relayhost: '[smtp.gmail.com]:465'
  smtp_sasl_auth_enable:  'yes'
  smtp_sasl_security_options: 'noanonymous'
  smtp_sasl_password_maps: 'hash:/etc/postfix/sasl/sasl_passwd'
  smtp_use_tls: 'yes'
  smtp_tls_security_level: 'encrypt'
  smtp_tls_wrappermode: 'yes'
  smtp_tls_CAfile: '/etc/ssl/certs/ca-certificates.crt'
  smtp_tls_session_cache_database: 'btree:${data_directory}/smtp_scache'

postfix_main: |
  compatibility_level = 3.6
  smtp_tls_CApath=/etc/ssl/certs
  smtp_tls_security_level = encrypt
  smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
  myhostname = mail.lan
  alias_maps = hash:/etc/aliases
  alias_database = hash:/etc/aliases
  myorigin = /etc/mailname
  mydestination =
  relayhost = [smtp.gmail.com]:465
  mynetworks = 127.0.0.0/8 192.168.10.0/24 192.168.30.0/24 192.168.31.0/24
  mailbox_size_limit = 0
  inet_interfaces = all
  inet_protocols = ipv4
  smtp_generic_maps = hash:/etc/postfix/generic
  smtp_sasl_auth_enable = yes
  smtp_sasl_security_options = noanonymous
  smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
  smtp_use_tls = yes
  smtp_tls_wrappermode = yes
  smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

postfix_aliases: |
  root@mail.lan rolf+root@amfelt.dk
  pve@mail.lan rolf+pve@amfelt.dk
  pbs@mail.lan rolf+pbs@amfelt.dk

postfix_generic: |
  root@mail.lan rolf+root@amfelt.dk
  pve@mail.lan rolf+pve@amfelt.dk
  pbs@mail.lan rolf+pbs@amfelt.dk

postfix_sasl_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37363834323530393034643834313933613034343864363139333635333439323662396637393036
          3166343366303964653966336461363963396430393361380a656238383938393033303630336635
          65313066336266623036323132663135346639656230613139353031376235626337396333373230
          6535333164363833650a633162343563313561616263363430643335333533343066336636393133
          65306166333064303034656631653232663237616531353062616430343833376635313035383063
          32336263633166393463646636656437383264653161306131616233626132393938343062666235
          313432336230373032313964666332666232
