---
  - name: Folder | Create | Backup
    tags: docker_install
    file:
      path: /home/deploy/{{ item.dir }}
      state: directory
      owner: deploy
      group: deploy
      mode: 0755
    with_items:
      - { dir: 'backup' } 

  - name: Docker | Archive | Portainer - container image as a tarball exists
    tags: dockbackup_docker_dataer_archive_images
    stat:
      path: /home/deploy/backup/{{ ansible_date_time.date }}_portainer_ce_latest.tar
    register: portainer_backup_file

  - name: Docker | Archive | Portainer  - container image as a tarball  
    tags: docker_archive_images
    docker_image:
      name: portainer/portainer-ce:latest
      archive_path: /home/deploy/backup/{{ ansible_date_time.date }}_portainer_ce_latest.tar
      source: pull
      state: present
    when: not portainer_backup_file.stat.exists
  
  - name: Docker | Archive | Watchtower - container image as a tarball exists
    tags: docker_archive_images
    stat:
      path: /home/deploy/backup/{{ ansible_date_time.date }}_watchtower_latest.tar
    register: watchtower_backup_file
  
  - name: Docker | Archive | Watchtower -  image as a tarball
    tags: docker_archive_images
    docker_image:
      name: containrrr/watchtower:latest
      archive_path: /home/deploy/backup/{{ ansible_date_time.date }}_watchtower_latest.tar
      source: pull
      state: present
    when: not watchtower_backup_file.stat.exists

  - name: Docker | Archive | Homer - container image as a tarball exists
    tags: docker_archive_images
    stat:
      path: /home/deploy/backup/{{ ansible_date_time.date }}_homer_latest.tar
    register: homer_backup_file

  - name: Docker | Archive | Homer - container image as a tarball
    tags: docker_archive_images
    docker_image:
      name: b4bz/homer:latest
      archive_path: /home/deploy/backup/{{ ansible_date_time.date }}_homer_latest.tar
      source: pull
      state: present
    when: not homer_backup_file.stat.exists
  
  - name: Docker | Archive | Uptime-Kuma - container image as a tarball exists
    tags: docker_archive_images
    stat:
      path: /home/deploy/backup/{{ ansible_date_time.date }}_uptime_kuma_latest.tar
    register: uptime_kuma_backup_file

  - name: Docker | Archive | Uptime-Kuma - container image as a tarball
    tags: docker_archive_images
    docker_image:
      name: louislam/uptime-kuma:latest
      archive_path: /home/deploy/backup/{{ ansible_date_time.date }}_uptime_kuma_latest.tar
      source: pull
      state: present
    when: not uptime_kuma_backup_file.stat.exists

