---
  - name: Docker | Deploy | Uptime-Kuma
    tags: docker_install
    community.docker.docker_container:
      name: uptime-kuma
      image: louislam/uptime-kuma:latest
      ports: 
        - "3001:3001"
      volumes:
        - /portainer/config/uptime-kuma:/app/data
      restart_policy: unless-stopped
  
  - name: get file stat to be able to perform check in the following task
    stat: path=/portainer/config/uptime-kuma/copy.txt
    register: kuma_file

  - name: Docker | Stop | Uptime-Kuma
    tags: docker_install
    community.docker.docker_container:
      name: uptime-kuma
      image: louislam/uptime-kuma:latest
      state: stopped
    when: not kuma_file.stat.exists  
  

  - name: Docker | Uptime-Kuma | config files
    tags: docker_install
    copy:
      src: files/{{ item.src }}
      dest: /{{ item.dest }}
      mode: 0644
    with_items:
      - { src: 'uptime-kuma/kuma.db', dest: 'portainer/config/uptime-kuma/kuma.db' }
      - { src: 'uptime-kuma/copy.txt', dest: 'portainer/config/uptime-kuma/copy.txt' }
    when: not kuma_file.stat.exists
  
  - name: Docker | Restart | Uptime-Kuma
    tags: docker_install
    community.docker.docker_container:
      name: uptime-kuma
      image: louislam/uptime-kuma:latest
      restart: yes
    when: not kuma_file.stat.exists