---  
  - name: Folder | Create | PI monitor
    tags: docker_install
    file:
      path: /portainer/config//{{ item.dir }}
      state: directory
      owner: root
      group: root
      mode: 0777
    with_items:
      - { dir: 'docker_pi_monitor' } 
      - { dir: 'grafana-data' } 
      - { dir: 'prometheus-data' } 

  - name: Docker | Pi_Monitor | config files
    tags: docker_install
    copy:
      src: files/{{ item.src }}
      dest: /{{ item.dest }}
      owner: root
      group: root
      mode: 0777
    with_items:
      - { src: 'pi_monitor/docker-compose.yml', dest: '/portainer/config/docker_pi_monitor/docker-compose.yml' }
      - { src: 'pi_monitor/prometheus/prometheus.yml', dest: '/portainer/config/prometheus-data/prometheus.yml' }

  - name: Deploy stack from a compose file
    community.docker.docker_compose:
        project_name: Pi Monitor
        project_src: /portainer/config/docker_pi_monitor/
        state: present
        
