---
- name: Install package
  tags: ufw
  package:
    state: latest
    name: ufw
  notify:
    - restart_ufw

# reset
- name: rest ufw rules
  include_tasks: ufw_reset.yml
  when: 
    - resetufw is defined
    - resetufw == true

# dns pi-hole
- name: allow 81 pihole (tcp)
  tags: ufw
  ufw:
    comment: allow 81 pihole  (tcp)
    rule: allow
    port: '81'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true

- name: allow dns pihole (tcp)
  tags: ufw
  ufw:
    comment: allow dns pihole (tcp)
    rule: allow
    port: '53'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true

- name: allow dns pihole (udp)
  tags: ufw
  ufw:
    comment: allow dns pihole (udp)
    rule: allow
    port: '53'
    proto: udp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_pihole is defined
    - enable_pihole == true

# web server
- name: web server allow http (80)
  tags: ufw
  ufw:
    comment: web server allow http (80)
    rule: allow
    port: '80'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_web80 is defined
    - enable_web80 == true

- name: web server allow https (443)
  tags: ufw
  ufw:
    comment: web server allow https (443)
    rule: allow
    port: '443'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_web443 is defined
    - enable_web443 == true

# Portainer
- name: Portainer (9000)
  tags: ufw
  ufw:
    comment: Portainer (9000)
    rule: allow
    port: '9000'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_portainer is defined
    - enable_portainer == true

# Cockpit
- name: Cockpit (9090)
  tags: ufw
  ufw:
    comment: Cockpit (9001)
    rule: allow
    port: '9090'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_cockpit is defined
    - enable_cockpit == true

# Crowdsec
- name: Crowdsec (6060)
  tags: ufw
  ufw:
    comment: Crowdsec (6060)
    rule: allow
    port: '6060'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true

# Crowdsec
- name: Crowdsec (6080)
  tags: ufw
  ufw:
    comment: Crowdsec (6080)
    rule: allow
    port: '6080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true

# Crowdsec
- name: Crowdsec (8080)
  tags: ufw
  ufw:
    comment: Crowdsec (8080)
    rule: allow
    port: '8080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec == true

# all rules set, enable
- name: enable firewall
  ufw:
    logging: on
    state: enabled
    
