---
- name: essential-debian | Update apt packages cache (Debian and Ubuntu)
  ansible.builtin.apt:
    upgrade: false
    autoremove: false
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  tags:
    - update_cache
