- name: Install oracle-instantclient-release-el8 packages ora8
  ansible.builtin.dnf:
    name: oracle-instantclient-release-el8
    state: present
    update_cache: true
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: Install oracle-instantclient-basic packages ora8
  ansible.builtin.dnf:
    name: oracle-instantclient-basic
    state: present
    update_cache: true
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: Install oracle-instantclient-sqlplus packages ora8
  ansible.builtin.dnf:
    name: oracle-instantclient-sqlplus
    state: present
    update_cache: true
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: Export PATH oracle
  ansible.builtin.shell: "echo export PATH=/usr/lib/oracle/21/client64/bin:$PATH"
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: Copy sqlnet.ora
  ansible.builtin.copy:
    src: files/ora/sqlnet.ora
    dest: /usr/lib/oracle/21/client64/lib/network/admin/sqlnet.ora
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: Copy tnsnames.ora
  ansible.builtin.copy:
    src: files/ora/tnsnames.ora
    dest: /usr/lib/oracle/21/client64/lib/network/admin/tnsnames.ora
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"
