---
- name: Update apt packages (Debian and Ubuntu)
  when: ansible_os_family | lower == "debian"
  ansible.builtin.apt:
    upgrade: false
    autoremove: false
    update_cache: true
    cache_valid_time: 3600

# extra packages
- name: Install extra packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present
  when: enable_extra_packages | d(false) | bool

# packages net-tools
- name: Install extra packages net-tools
  ansible.builtin.package:
    name: "{{ extra_packages_nettools }}"
    state: present
  when: enable_extra_packages_nettools | d(false) | bool

# Cockpit
- name: Install Cockpit
  ansible.builtin.package:
    name: cockpit
    state: present
  when: enable_cockpit | d(false) | bool
- name: Remove Cockpit
  ansible.builtin.package:
    name: cockpit
    state: absent
  when: not enable_cockpit | d(false) | bool

# auditd
- name: Install auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: present
  when: enable_auditd | d(false) | bool
- name: Remove auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: absent
  when: not enable_auditd | d(false) | bool

# rkhunter
- name: Install rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: present
  when: enable_rkhunter | d(false) | bool
- name: Remove rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: absent
  when: not enable_rkhunter | d(false) | bool

# aide
- name: Install aide
  ansible.builtin.package:
    name:
      - aide
    state: present
  when: enable_aide | d(false) | bool
- name: Remove aide
  ansible.builtin.package:
    name:
      - aide
    state: absent
  when: not enable_aide | d(false) | bool

# Lynis
- name: Install Lynis from GIT
  ansible.builtin.git:
    repo: "https://github.com/CISOfy/lynis.git"
    version: "3.0.8"
    dest: /opt/lynis
  when: enable_lynis | d(false) | bool
- name: Remove Lynis
  ansible.builtin.file:
    path: /opt/lynis
    state: absent
  when: not enable_lynis | d(false) | bool
