---    
  - name: Create a login user
    become: yes
    user:
      name: "{{ username_sec }}"
      password: "{{ userpassword_sec }}"
      groups: 
        - "{{ sudo_group }}"
        - users
      state: present
      append: true
  
  - name: Ensure group "{{ username_sec }}" exists
    become: yes
    group:
      name: "{{ username_sec }}"
      state: present
  
  - name: Allow 'sudo' group to have passwordless sudo
    become: yes
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%{{ sudo_group }}'
      line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: Copy the public SSH key 
    become: yes
    authorized_key:
      user: "{{ username_sec}}"
      state: present
      key: "{{ ssh_public_key }}"

  - name: Set the default shell
    user: 
      name: "{{ username_sec }}"
      shell: "{{ shell }}"

  - name: Suppress login messages
    file:
      name: /home/{{ username_sec }}/.hushlogin
      mode: 0644
      state: touch
      modification_time: preserve
      access_time: preserve
  
  - name: copy '.bash_aliases' file.
    copy:
      src: files/dot_files/.bash_aliases
      dest: /home/{{ username_sec }}/.bash_aliases
      owner: {{ username_sec }}
      mode: 0644
  
  - name: copy '.bash_aliases' file to root user.
    copy:
      src: files/dot_files/.bash_aliases
      dest: /root/.bash_aliases
      owner: root
      mode: 0644
  


      

 
