---
- name: Install a list of dependencies apt.
  apt:
    pkg: 
    - apt-transport-https
    - curl
    - nano
    - htop
    - unzip
    - git
    - python3
    - python3-pip
    - nmap
    - iperf
    - dnsutils
    - net-tools
    - jq
