---
- name: Install a list of dependencies apt.
  apt:
    pkg: 
    - apt-transport-https
    - ca-certificates
    - curl
    - nano
    - htop
    - unzip
    - nmap
    - dnsutils
    - net-tools
    - rsync
    - netcat
    - git
    - python3
    - python3-pip