---
# User settings
username: deploy
userpassword: "Changeme2022!" # Only for testing
sudo_group: sudo
ssh_public_key: "{{ lookup('file', '~/.ssh/deploy.pub') }}"
shell: /bin/bash
dns_nameservers: ["1.1.1.3", "1.0.0.3"]
keyboard_layout: dk
guid: "1000"
