# tasks file
---

- name: Allow outgoing
  community.general.ufw:
    comment: default allow outgoing
    default: allow
    direction: outgoing
  when: enable_ufw | d(false) | bool

- name: Deny outgoing
  community.general.ufw:
    comment: default allow outgoing
    default: deny
    direction: outgoing
  when: enable_ufw | d(false) | bool

- name: Disallow incoming
  community.general.ufw:
    comment: default deny incoming
    default: deny
    direction: incoming
  when: enable_ufw | d(false) | bool

- name: Allow necessary ports in UFW
  community.general.ufw:
    rule: allow
    direction: "{{ item.direction | default('in') }}"
    from_ip: "{{ item.src | default('any') }}"
    to_ip: "{{ item.dest | default('any') }}"
    port: "{{ item.port | default('') }}"
    proto: "{{ item.proto | default('any') }}"
    comment: "{{ item.comment }}"
  loop: "{{ open_ports }}"
  notify: Reloadufw
  when: enable_ufw | d(false) | bool

## maby this shuld be a handler.
# - name: configure | reset
#   community.general.ufw:
#     state: reset
#   when: configuration is changed
#   tags: ufw-configure-reset
