# tasks file
---
- name: fix dropped ssh sessions | configure kernel
  ansible.posix.sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: '1'
    state: present
    sysctl_set: true
    reload: true
