---
- name: Install package UFW
  tags: ufw
  ansible.builtin.package:
    state: present
    name: ufw
  notify:
    - Reloadufw
  when: enable_ufw | d(false) | bool

- name: Disable IPv6 for UFW
  ansible.builtin.replace:
    path: "/etc/default/ufw"
    regexp: 'IPV6=yes'
    replace: 'IPV6=no'
    backup: true
  when: enable_ufw | d(false) | bool
