# tasks file
---
- name: Install package ufw
  tags: ufw
  ansible.builtin.package:
    state: present
    name: ufw
  notify:
    - Reload ufw
  when:
    - enable_ufw is defined
    - enable_ufw

- name: Ufw disable IPv6
  ansible.builtin.replace:
    path: "/etc/default/ufw"
    regexp: 'IPV6=yes'
    replace: 'IPV6=no'
    backup: true
