---
- name: Install UFW
  ansible.builtin.import_tasks: install.yml

- name: Configure UFW
  ansible.builtin.import_tasks: configure.yml

# - name: Fix dropped ssh sessions
#   ansible.builtin.import_tasks: fix-dropped-ssh-sessions.yml

- name: Set logging for UFW
  community.general.ufw:
    logging: 'on'

- name: Enable Firewall UFW
  community.general.ufw:
    state: enabled
  notify:
    - Reloadufw
  when: enable_ufw | d(false) | bool
