---
- name: Install package ufw
  tags: ufw
  ansible.builtin.package:
    state: present
    name: ufw
  notify:
    - Restart_ufw
  when:
    - enable_ufw is defined
    - enable_ufw

- name: Allow outgoing
  community.general.ufw:
    comment: default allow outgoing
    default: allow
    direction: outgoing
  when:
    - enable_ufw is defined
    - not enable_ufw_deny_out

- name: Deny outgoing
  community.general.ufw:
    comment: default allow outgoing
    default: deny
    direction: outgoing
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out

- name: Disallow incoming
  community.general.ufw:
    comment: default deny incoming
    default: deny
    direction: incoming
  when:
    - enable_ufw is defined
    - enable_ufw

# reset UFW
- name: Reset UFW
  community.general.ufw:
    logging: true
    state: reset
  notify:
    - Restart_ufw
  when:
    - resetufw is defined
    - resetufw

- name: Out allow ssh 22
  community.general.ufw:
    comment: Out allow ssh 22
    rule: allow
    direction: out
    port: '22'
    proto: tcp
  when:
    - enable_ufw is defined
    - enable_out_ssh_22

- name: Out allow 53 DNS
  community.general.ufw:
    comment: Out allow dns 53
    rule: allow
    direction: out
    port: '53'
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out

- name: Out allow 123 NTP
  community.general.ufw:
    comment: Out allow 123 Ntp
    rule: allow
    direction: out
    port: '123'
    proto: udp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out

- name: Out allow 80 http
  community.general.ufw:
    comment: Out allow web 80
    rule: allow
    direction: out
    port: '80'
    proto: tcp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out

- name: Out allow 443 https
  community.general.ufw:
    comment: Out allow https 443
    rule: allow
    direction: out
    port: '443'
    proto: tcp
  when:
    - enable_ufw is defined
    - enable_ufw_deny_out

# SSH
- name: Grant ssh access
  community.general.ufw:
    comment: In allow ssh 22
    rule: allow
    direction: in
    port: '22'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_ufw is defined
    - enable_ufw

# Web server
- name: Web server allow http (80)
  tags: ufw
  community.general.ufw:
    comment: In web server allow http (80)
    rule: allow
    port: '80'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_web80 is defined
    - enable_web80
    - enable_ufw

- name: Web server allow https (443)
  tags: ufw
  community.general.ufw:
    comment: In web server allow https (443)
    rule: allow
    port: '443'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_web443 is defined
    - enable_web443
    - enable_ufw

# DNS server
- name: DNS 53 udp
  tags: ufw
  community.general.ufw:
    comment: In DNS udp (53)
    rule: allow
    port: '53'
    proto: udp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_dns53 is defined
    - enable_dns53
    - enable_ufw

 # DNS server
- name: DNS 53 tcp
  tags: ufw
  community.general.ufw:
    comment: In DNS tcp (53)
    rule: allow
    port: '53'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_dns53 is defined
    - enable_dns53
    - enable_ufw

# Portainer
- name: Portainer (9000)
  tags: ufw
  community.general.ufw:
    comment: In Portainer (9000)
    rule: allow
    port: '9000'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_portainer is defined
    - enable_portainer
    - enable_ufw

# Cockpit
- name: Cockpit (9090)
  tags: ufw
  community.general.ufw:
    comment: In Cockpit (9090)
    rule: allow
    port: '9090'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_cockpit is defined
    - enable_cockpit
    - enable_ufw

# Crowdsec
- name: Crowdsec (6060)
  tags: ufw
  community.general.ufw:
    comment: In Crowdsec (6060)
    rule: allow
    port: '6060'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec

# Crowdsec
- name: Crowdsec (6080)
  tags: ufw
  community.general.ufw:
    comment: In Crowdsec (6080)
    rule: allow
    port: '6080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec
    - enable_ufw

# Crowdsec
- name: Crowdsec (8080)
  tags: ufw
  community.general.ufw:
    comment: In Crowdsec (8080)
    rule: allow
    port: '8080'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_crowdsec is defined
    - enable_crowdsec
    - enable_ufw

# Littlelink
- name: Littlelink (8001)
  tags: ufw
  community.general.ufw:
    comment: In Littlelink (8001)
    rule: allow
    port: '8001'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_littlelink is defined
    - enable_littlelink
    - enable_ufw

# Uptime-Kuma
- name: Uptime-Kuma (3001)
  tags: ufw
  community.general.ufw:
    comment: In Uptime-Kuma (3001)
    rule: allow
    port: '3001'
    proto: tcp
    src: '{{ item }}'
  loop: "{{ local_lan_ufw }}"
  when:
    - enable_uptimekuma is defined
    - enable_uptimekuma
    - enable_ufw


# Docker
- name: DockerNet 172.17.x.x allow in
  tags: ufw
  community.general.ufw:
    comment: DockerNet Allow in
    rule: allow
    direction: in
    src: '172.17.0.0/16'
    to_ip: '172.17.0.0/16'
  when:
    - enable_docker is defined
    - enable_docker
    - enable_ufw

# Docker
- name: DockerNet 172.17.x.x allow out
  tags: ufw
  community.general.ufw:
    comment: DockerNet Allow out
    rule: allow
    direction: out
    src: '172.17.0.0/16'
    to_ip: '172.17.0.0/16'
  when:
    - enable_docker is defined
    - enable_docker
    - enable_ufw

- name: Enable Firewall ufw
  community.general.ufw:
    logging: "on"
    state: enabled
  notify:
    - Restart_ufw
  when:
    - enable_ufw is defined
    - enable_ufw
