---
- name: Fix dropped ssh sessions
  ansible.builtin.import_tasks: fix-dropped-ssh-sessions.yml

- name: Install UFW
  ansible.builtin.import_tasks: install.yml

- name: Configure
  ansible.builtin.import_tasks: configure.yml

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Enable Firewall ufw
  community.general.ufw:
    state: enabled
  notify:
    - Reload ufw
  when:
    - enable_ufw is defined
    - enable_ufw
