---
- name: Ensure NFS utilities are installed.
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ nfsclient_nfs_connect }}"
    path: "{{ nfsclient_local_folder }}"
    opts: rw,sync
    boot: false
    state: mounted
    fstype: nfs
