---
- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Set timezone to Europe/Copenhagen.
      timezone:
        name: Europe/Copenhagen
    
    - name: stop service cups-browsed on debian, if running.
      systemd: name=cups-browsed state=stopped enabled=false
    
    - name: stop service cups on debian, if running.
      systemd: name=cups state=stopped enabled=false
        
    - name: Update cache on OS.
      include_tasks: tasks/update-cache-os.yml

  roles:
       - geerlingguy.pip

  tasks:

  - name: Update cache on OS.
      include_tasks: tasks/debian_pkg.yml


  