---
- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes cache_valid_time=3600
      changed_when: False

  tasks:
  - name: Install a list of dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - nmap
        - curl
        - iperf
        - apt-transport-https
        - dnsutils
        - nano
        - net-tools
        - jq
        - tree
        - htop
        - unzip
  
  - name: copy .bash_aliases file
    become: false
    copy:
     src: files/.bash_aliases
     dest: /home/rolf/.bash_aliases
     owner: rolf
     group: rolf

  - name: Creating a home/bin and home/Tools
    become: false
    file:
      path: "/home/rolf/Tools"
      state: directory
      owner: rolf
      group: rolf
    file:
      path: "/home/rolf/bin"
      state: directory
      owner: rolf
      group: rolf
  
  - name: copy mycrt script to bin
    become: false
    copy:
     src: files/mycrt
     dest: /home/rolf/bin/mycrt
  

