---
# Role settings
configure_settings: false
configure_registry: false
remove_persistent_data: false
remove_existing_container: false
persistent_data_path: "{{ docker_dir }}:/data"
container_image: portainer/portainer:{{ version }}
container_name: portainer
container_labels: {}
container_network:
container_restart_policy: always
container_recreate: false
auth_method: 1
# Portainer version
version: latest

# Networking
host_ip: 192.168.56.22
host_port: 9000
container_ports:
  - "9000:9000"

# Admin User
admin_user: admin
admin_password: "{{ portainer_password_sec }}"

# Endpoints
endpoint_name: local
