---
- name: Start nftables services
  service:
    name: nftables
    state: started
    enabled: yes

- name: Copy crowdsec repo file into place.
  template:
    src: templates/crowdsec_crowdsec.j2
    dest: /etc/yum.repos.d/crowdsec_crowdsec.repo
    owner: root
    group: root
    mode: 0644

- name: install Crowdsec
  dnf: 
    update_cache: yes
    name: crowdsec
    state: present

- name: Crowdsec-firewall-bouncer-nftables
  dnf: 
    update_cache: yes
    name: crowdsec-firewall-bouncer-nftables 
    state: present
    