---
- name: Make sure the Portainer simple container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "portainer/portainer:latest"
    pull: true
    state: "started"
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/{{ container_name }}_data:/data"
    restart_policy: unless-stopped
