---
# extra packages
- name: Install epel-release
  dnf:
    name: epel-release
    state: present
  when: ansible_distribution_major_version == '8'

- name: Install epel-release oracle
  yum:
    name: oracle-epel-release-el7
    state: present
  when: 
    - ansible_distribution_major_version == '7'
    - ansible_distribution == "OracleLinux"
  
# extra packages
- name: Install extra packages 8
  dnf:
    name: "{{ extra_packages }}"
    state: present
  when: ansible_distribution_major_version == '8'

- name: Install extra packages 7
  yum:
    name: "{{ extra_packages }}"
    state: present
  when: ansible_distribution_major_version == '7'
