---
- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family | lower == "debian"
  apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Install Cockpit
  package:
    name: cockpit
    state: present
  when: 
    - enable_cockpit is defined
    - enable_cockpit == true

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'


