---
- name: Update apt packages (Debian and Ubuntu)
  apt:
    upgrade: no
    autoremove: no
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - system
    - update_cache

# extra packages
- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present
  tags:
    - system
    - extra_packages
    
# packages net-tools
- name: Install extra packages net-tools
  package:
    name: "{{ extra_packages_nettools }}"
    state: present
  tags:
    - system
    - extra_packages_nettools