---
# extra packages
- name: Install epel-release
  dnf:
    name: epel-release
    state: present
  when: 
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"
  
- name: Install extra packages ora8
  dnf:
    name: "{{ extra_packages }}"
    state: present
    update_cache: yes
  when: 
    - ansible_distribution_major_version | int in [8]
    - ansible_distribution == "OracleLinux"

- name: uncomment base URL line in repo file oracle-epel-ol9.repo
  lineinfile:
    path: "/etc/yum.repos.d/oracle-epel-ol9.repo"
    search_string: '#baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/developer/EPEL/$basearch/'
    line: "baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/developer/EPEL/$basearch/"
    backup: no
    owner: root
    group: root
    mode: 0644
  when: 
    - ansible_distribution_major_version | int in [9]
    - ansible_distribution == "OracleLinux"

- name: uncomment base URL line in repo file oracle-linux-ol9.repo
  lineinfile:
    path: "/etc/yum.repos.d/oracle-linux-ol9.repo"
    search_string: "{{ item.search_string }}"
    line: "{{ item.line }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  with_items:
  - search_string: "#baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/baseos/latest/$basearch/"
    line: "baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/baseos/latest/$basearch/"
  - search_string: "#baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/appstream/$basearch/"
    line: "baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/appstream/$basearch/"
  when: 
    - ansible_distribution_major_version | int in [9]
    - ansible_distribution == "OracleLinux"

- name: uncomment base URL line in repo file uek-ol9.repo
  lineinfile:
    path: "/etc/yum.repos.d/uek-ol9.repo"
    search_string: "{{ item.search_string }}"
    line: "{{ item.line }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  with_items:
  - search_string: "#baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/UEKR7/$basearch/"
    line: "baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/UEKR7/$basearch/"
  - search_string: "#baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/RDMA/$basearch/"
    line: "baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/RDMA/$basearch/"
  when: 
    - ansible_distribution_major_version | int in [9]
    - ansible_distribution == "OracleLinux"
    
- name: Install extra packages ora9
  dnf:
    name: "{{ extra_packages }}"
    state: present
    update_cache: yes
  when: 
    - ansible_distribution_major_version | int in [9]
    - ansible_distribution == "OracleLinux"


- name: Install epel-release oracle
  yum:
    name: oracle-epel-release-el7
    state: present
  when: 
    - ansible_distribution_major_version | int in [7]
    - ansible_distribution == "OracleLinux"

- name: Install extra packages 7
  yum:
    name: "{{ extra_packages }}"
    state: present
  when: 
    - ansible_distribution_major_version | int in [7]
    - ansible_distribution == "OracleLinux"

