---
- include_tasks: essential-redhat.yml
  when: ansible_os_family | lower == 'redhat'

- include_tasks: essential-debian.yml
  when: ansible_os_family | lower == 'debian'

- include_tasks: yeet_snaps.yml
  when: ansible_os_family | lower == 'debian'

- include_tasks: user.yml

- include_tasks: disable_ipv6.yml