---
- name: Essential-redhat
  ansible.builtin.include_tasks: essential-redhat.yml
  when: ansible_os_family | lower == 'redhat'

- name: Essential-debian
  ansible.builtin.include_tasks: essential-debian.yml
  when: ansible_os_family | lower == 'debian'

- name: Del snap
  ansible.builtin.include_tasks: del_snap.yml
  when: ansible_os_family | lower == 'debian'

- name: User
  ansible.builtin.include_tasks: user.yml

- name: Disable_ipv6
  ansible.builtin.include_tasks: disable_ipv6.yml

- name: Other
  ansible.builtin.include_tasks: other.yml
