---
- name: Update apt packages (Debian and Ubuntu)
  when: ansible_os_family | lower == "debian"
  ansible.builtin.apt:
    upgrade: false
    autoremove: false
    update_cache: true
    cache_valid_time: 3600

# extra packages
- name: Install extra packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present
  when:
    - enable_extra_packages is defined
    - enable_extra_packages

# packages net-tools
- name: Install extra packages net-tools
  ansible.builtin.package:
    name: "{{ extra_packages_nettools }}"
    state: present
  when:
    - enable_extra_packages_nettools is defined
    - enable_extra_packages_nettools

# Cockpit
- name: Install Cockpit
  ansible.builtin.package:
    name: cockpit
    state: present
  when:
    - enable_cockpit is defined
    - enable_cockpit

- name: Remove Cockpit
  ansible.builtin.package:
    name: cockpit
  when:
    - enable_cockpit is defined
    - not enable_cockpit

# auditd
- name: Install auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: present
  when:
    - enable_auditd is defined
    - enable_auditd

- name: Remove auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: absent
  when:
    - enable_auditd is defined
    - not enable_auditd

# rkhunter
- name: Install rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: present
  when:
    - enable_rkhunter is defined
    - enable_rkhunter

- name: Remove rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: absent
  when:
    - enable_rkhunter is defined
    - not enable_rkhunter

# aide
- name: Install aide
  ansible.builtin.package:
    name:
      - aide
    state: present
  when:
    - enable_aide is defined
    - enable_aide

- name: Remove aide
  ansible.builtin.package:
    name:
      - aide
    state: absent
  when:
    - enable_aide is defined
    - not enable_aide

# Lynis
- name: Git Clone Lynis
  ansible.builtin.git:
    repo: 'https://github.com/CISOfy/lynis.git'
    version: 'HEAD'
    dest: /opt/lynis
  when:
    - enable_lynis is defined
    - enable_lynis

- name: Remove Lynis
  ansible.builtin.file:
    path: /opt/lynis
    state: absent
  when:
    - enable_lynis is defined
    - not enable_lynis
