---
- name: Update apt packages (Debian and Ubuntu)
  when: ansible_os_family | lower == "debian"
  ansible.builtin.apt:
    upgrade: false
    autoremove: false
    update_cache: true
    cache_valid_time: 3600

# extra packages
- name: Install extra packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present
  when:
    - enable_extra_packages is defined
    - enable_extra_packages == true

# packages net-tools
- name: Install extra packages net-tools
  ansible.builtin.package:
    name: "{{ extra_packages_nettools }}"
    state: present
  when:
    - enable_extra_packages_nettools is defined
    - enable_extra_packages_nettools == true

# Cockpit
- name: Install Cockpit
  ansible.builtin.package:
    name: cockpit
    state: present
  when:
    - enable_cockpit is defined
    - enable_cockpit == true

- name: Remove Cockpit
  ansible.builtin.package:
    name: cockpit
  when:
    - diable_cockpit is defined
    - diable_cockpit == true

# auditd
- name: Install auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: present
  when:
    - enable_auditd is defined
    - enable_auditd == true

- name: Remove auditd
  ansible.builtin.package:
    name:
      - auditd
      - libauparse0
      - audispd-plugins
    state: absent
  when:
    - diable_auditd is defined
    - diable_auditd == true

# rkhunter
- name: Install rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: present
  when:
    - enable_rkhunter is defined
    - enable_rkhunter == true
    
- name: Remove rkhunter
  ansible.builtin.package:
    name:
      - rkhunter
    state: absent
  when:
    - diable_rkhunter is defined
    - diable_rkhunter == true

# aide
- name: Install aide
  ansible.builtin.package:
    name:
      - aide
    state: present
  when:
    - enable_aide is defined
    - enable_auditd == true

- name: Remove aide
  ansible.builtin.package:
    name:
      - aide
    state: absent
  when:
    - diable_aide is defined
    - diable_auditd == true

# Lynis
- name: Git Clone Lynis
  ansible.builtin.git:
    repo: 'https://github.com/CISOfy/lynis.git'
    dest: /opt/lynis
    update: true
  when:
    - enable_lynis is defined
    - enable_lynis == true

- name: Remove Lynis
  ansible.builtin.file:
    path: /opt/lynis
    state: absent
  when:
    - diable_lynis is defined
    - diable_lynis == true
