---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes
  
  # collections:
  #   - community.docker

  roles:
    - geerlingguy.security
    - geerlingguy.ntp
    - geerlingguy.docker
  
    - role: system
      tags: 
        - system
    
    - role: docker
      tags: 
        - docker
    
    - role: network/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole 
        - containers
    
    - role: network/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    # - role: network/swag
    #   tags: 
    #     - swag
    #     - containers
    #   when: enable_swag | default(False)

    - role: containers/system/watchtower
      tags:
        - watchtower
        - containers
      when: enable_watchtower
    
    - role: containers/system/portainer
      tags:
        - portainer
        - containers
      when: enable_portainer
                
    - role: security/crowdsec
      tags:
        - crowdsec
      when: enable_crowdsec
  

