---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: update debian chache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
  
  roles:

    - role: system
      tags:
        - system
        - security
        - users

    - role: geerlingguy.security
      tags:
        - system
        - security
    
    - role: geerlingguy.ntp
      tags:
        - system
        - ntp
    
    - role: geerlingguy.pip
      tags:
        - containers
        - pip
      when: enable_portainer or enable_watchtower or enable_pihole
      
    - role: geerlingguy.docker
      tags:
        - containers
        - docker
      when: enable_portainer or enable_watchtower or enable_pihole
             
    - role: security/ufw
      tags:
        - ufw
        - security
      when: enable_ufw | default(False)

    - role: security/crowdsec
      tags:
        - crowdsec
        - security
      when: enable_crowdsec | default(False)

    - role: containers/portainer
      tags:
        - portainer
        - containers
      when: enable_portainer | default(False)

    - role: containers/watchtower
      tags:
        - watchtower
        - containers
      when: enable_watchtower | default(False)
          
    - role: containers/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)
  
  tasks:
    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - system
        - security
      when: ansible_os_family | lower == "debian" and enable_osupgrade | default(False)
      

- hosts: pi01.test
  gather_facts: yes
  become: yes

  roles:
             
    - role: containers/pihole
      tags:
        - pihole 
        - containers
      when: enable_pihole | default(False)
    

