---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: update debian chache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
  
  roles:

    - role: system
      tags:
        - system
        - security
        - users

    - role: geerlingguy.security
      tags:
        - system
        - security
    
    - role: geerlingguy.ntp
      tags:
        - system
        - ntp
    
    - role: geerlingguy.pip
      tags:
        - containers
        - pip
        - portainer
        - watchtower
        - pihole
      
    - role: geerlingguy.docker
      tags:
        - containers
        - docker
        - portainer
        - watchtower
        - pihole
             
    - role: ufw
      tags:
        - ufw
        - security

    - role: crowdsec
      tags:
        - crowdsec
        - security

    - role: containers/portainer
      tags:
        - portainer
        - containers

    - role: containers/watchtower
      tags:
        - watchtower
        - containers
          
    - role: containers/wireguard
      tags: 
        - wireguard
        - containers  
  tasks:
    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - system
        - security
        - enable_osupgrade
      when: ansible_os_family | lower == "debian" 
      

- hosts: pi01.test
  gather_facts: yes
  become: yes

  roles:
             
    - role: containers/pihole
      tags:
        - dns
        - pihole 
        - containers

    

