---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: update debian chache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
  
  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.pip
    - geerlingguy.docker
    

    - role: system
      tags: 
        - system
    
    #- role: geerlingguy.pip
  
        
    - role: network/pihole
      tags:
        - pihole 
        - containers
      when: enable_pihole | default(False)
    
    - role: network/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: containers/system/watchtower
      tags:
        - watchtower
        - containers
      when: enable_watchtower | default(False)
    
    - role: containers/system/portainer
      tags:
        - portainer
        - containers
      when: enable_portainer | default(False)
                
    - role: security/crowdsec
      tags:
        - crowdsec
        - security
      when: enable_crowdsec | default(False)
  

