---
#
# Tasks and roles for all hosts
#
- hosts: pi_servers
  gather_facts: no
  become: yes
  
  collections:
    - community.docker

  roles:
    - geerlingguy.security
    - geerlingguy.ntp
    - geerlingguy.pip
    - geerlingguy.docker
  
    - role: system
      tags: 
        - system
    
    - role: docker
      tags: 
        - docker

    - role: security/crowdsec
      tags:
        - crowdsec
      when: enable_crowdsec
  

