- hosts: all
  gather_facts: yes
  become: yes
 
  roles:

    - role: system
      tags:
        - user

    - role: geerlingguy.security
      tags:
        - security
    
    - role: geerlingguy.ntp
      tags:
        - ntp
               
    - role: ufw
      tags:
        - ufw
        - security

    - role: crowdsec
      tags:
        - crowdsec
        - security

  tasks:
    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - system
        - security
      when: ansible_os_family | lower == "debian" and enable_osupgrade | default(False)
      


    

