- hosts: all
  gather_facts: yes
  become: yes

  pre_tasks: 
    - name: copy '/etc/resolv.conf' file to solve dns issues
      copy:
        src: files/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        mode: 0644
      tags: users
 
  roles:

    - role: system
      tags:
        - system
        - user
    
    - role: geerlingguy.security
      tags:
        - security
    
    - role: geerlingguy.ntp
      tags:
        - ntp 

    # - role: alf149.crowdsec
    #   tags:
    #     - crowdsec

