- name: Provision a new server on test og lab
  hosts: windows:proxmox:servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: system
      tags:
        - system
        - user
        - defaults
