---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - group_vars/secrets.yml
  
  roles:

    - role: system
      tags:
        - user
        - defaults

    - role: geerlingguy.security
      tags:
        - security
        - defaults

    - role: geerlingguy.ntp
      tags:
          - ntp
          - defaults

    - role: geerlingguy.pip
      tags:
        - containers

    - role: geerlingguy.docker
      tags:
        - containers

    - role: containers/portainer
      tags:
        - containers
        - portainer

    - role: containers/watchtower
      tags:
        - containers
        - watchtower

    - role: containers/uptime-kuma
      tags:
        - containers
        - uptime-kuma

    - role: containers/littlelink
      tags:
        - containers
        - littlelink
          
  tasks:
    
    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
      changed_when: False 


    

