- hosts: all
  gather_facts: yes
  become: yes

  roles:

    - role: system
    - role: geerlingguy.security
    - role: geerlingguy.ntp               
    - role: crowdsec_dev
    #- role: alf149.crowdsec
      tags:
        - crowdsec
    

