---
#
# Tasks and roles for all hosts
#
- name: Run on all hosts
  hosts: servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
      changed_when: false

  collections:

    - collection: devsec.hardening

  roles:

    - role: devsec.hardening.os_hardening
      vars:
      sysctl_overwrite:
        # Enable IPv4 traffic forwarding.
        net.ipv4.ip_forward: 1

    - role: system
      tags:
        - users
        - defaults

    - role: geerlingguy.security
      tags:
        - security
        - defaults
        - geerlingguy

    - role: geerlingguy.ntp
      tags:
        - ntp
        - defaults
        - geerlingguy

    - role: geerlingguy.clamav
      tags:
        - clamav
        - defaults
        - geerlingguy

#### SRV01.test ####
- name: Run on "srv01.test"
  hosts: srv01.test
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

#### SRV02.test ####
- name: Run on "srv02.test"
  hosts: srv02.test
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: geerlingguy.nfs
      tags:
        - nfs

    - role: geerlingguy.pip
      tags:
        - containers

    - role: geerlingguy.docker
      tags:
        - containers

    - role: portainer
      tags:
        - containers
        - portainer

    - role: watchtower
      tags:
        - containers
        - watchtower

    - role: gitea
      tags:
        - containers
        - gitea

    # - role: uptime-kuma
    #   tags:
    #     - containers
    #     - uptime-kuma

    # - role: littlelink
    #   tags:
    #     - containers
    #     - littlelink


