- hosts: all
  gather_facts: yes
  become: yes

  tasks: 
  
  #   - name: Get services facts
  #     service_facts:
  #   - debug: var=ansible_facts.services['crowdsec.service'] 
  #   - debug: var=ansible_facts.services['crowdsec-firewall-bouncer.service'] 
    
  
    ## https://crowdsec.net/blog/multi-server-setup/
    # edit on server 01 (lapi)      /etc/crowdsec/config.yaml                       listen_uri: 127.0.0.1:8080
    - name: Crowdsec ajust /etc/crowdsec/config.yaml listen_uri
      replace:
        path: "/etc/crowdsec/config.yaml"
        #after: "- type: ban"
        regexp: 'listen_uri: 127.0.0.1:8080'
        replace: "listen_uri: 0.0.0.0:8080"
        backup: yes
      when: crowdsec_lapi_ip is defined

    # edit on server 01 (lapi)      /etc/crowdsec/local_api_credentials.yaml
    - name: /etc/crowdsec/local_api_credentials.yaml
      replace:
        path: "/etc/crowdsec/config.yaml"
        #after: "- type: ban"
        regexp: 'url: http://127.0.0.1:8080'
        replace: "{{ crowdsec_lapi_ip }}"
        backup: yes
      when: crowdsec_lapi_ip is defined

    - name: Restart crowdsec
      service:
        name: crowdsec
        state: restarted



    # restart server 01 (lapi)      sudo systemctl restart crowdsec

    # server 2-3-4 
    # Edit to the ip of server 01   sudo cscli lapi register -u http://10.0.0.1:8080 

    # backup up of                  sudo cp /lib/systemd/system/crowdsec.service /etc/systemd/system/crowdsec.service
    # edit                          /etc/systemd/system/crowdsec.service
    #                               ExecStart=/usr/bin/crowdsec -c /etc/crowdsec/config.yaml -no-api

    # restart demon                 sudo systemctl daemon-reload
    # restart crowdsec              sudo systemctl restart crowdsec

    # list 
    #                               sudo cscli machines list
    #                               Get VALUE1 VALUE2..

    # validate                      sudo cscli machines validate VALUE1 VALUE2
    # restart                       sudo systemctl restart crowdsec

    