---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:
    - name: update debian chache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
  
  roles:

    - role: system
      tags:
        - users

    - role: geerlingguy.security
      tags:
        - security
    
    - role: geerlingguy.ntp
      tags:
        - ntp
    
    - role: geerlingguy.pip
      tags:
        - containers
        - pip
        - portainer
        - watchtower
        - pihole
      
    - role: geerlingguy.docker
      tags:
        - containers
        - docker
        - portainer
        - watchtower
        - pihole
             
    - role: ufw
      tags:
        - ufw

    # - role: alf149.crowdsec
    #   tags:
    #     - crowdsec

    - role: containers/portainer
      tags:
        - portainer
        - containers

    - role: containers/watchtower
      tags:
        - watchtower
        - containers
          
  tasks:
    
    # Cockpit
    - name: Install Cockpit
      package:
        name: cockpit
        state: present
      when: 
        - enable_cockpit is defined
        - enable_cockpit == true

    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - system
        - security
        - enable_osupgrade
      when: ansible_os_family | lower == "debian" 


    

