- hosts: all
  gather_facts: yes
  become: yes

  roles:

    - role: system
      tags:
        - system
        - user
    
    - role: geerlingguy.security
      tags:
        - security
    
    - role: geerlingguy.ntp
      tags:
        - ntp  
    
    - role: crowdsec_dev
      tags:
        - crowdsec
    

