---
#
# Tasks and roles for all hosts
#
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:
    - name: update ubuntu/debian chache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
      changed_when: False
  
  roles:

    - role: system
      vars:
        username: "{{ username_sec }}"
        userpassword: "{{ userpassword_sec }}" 
        sudo_group: sudo
        ssh_public_key: "{{ ssh_public_key_sec }}"
        shell: /bin/bash
        guid: "1000"
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: containers/portainer
    - role: containers/watchtower
    - role: containers/uptime-kuma
          
  tasks:
    
    - name: Upgrade apt packages (Debian and Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600

      when: ansible_os_family | lower == "debian" 


    

