---
#
# Tasks and roles for all hosts
#

- name: Run on allPROD-SERVERS
  hosts: prod-servers
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  pre_tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false

  roles:

    - role: system
      tags:
        - users
        - defaults

    - role: geerlingguy.security
      tags:
        - security
        - defaults

    - role: geerlingguy.ntp
      tags:
        - ntp
        - defaults

#### PI1.LAN ####
- name: Run on "pi1.lan"
  hosts: pi1.lan
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

#### PI2.LAN ####
- name: Run on "pi2.lan"
  hosts: pi2.lan
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

#### DOCKER01.LAN ####
- name: Run on "docker01.lan"
  hosts: docker01.lan
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: geerlingguy.pip
      tags:
        - containers

    - role: geerlingguy.docker
      tags:
        - containers

    - role: portainer
      vars:
        remove_persistent_data: false
        remove_existing_container: false
        # Networking
        host_ip: 192.168.30.151
        host_port: 9000
        container_ports:
          - "9000:9000"
        # Admin User
        admin_user: admin
        admin_password: "{{ portainer_password_prod_sec }}"
        # Endpoints
        endpoint_name: docker01.lan
      tags:
        - containers
        - portainer

    - role: watchtower
      tags:
        - containers
        - watchtower

#### SRV201.LAN ####
- name: Run on "srv201.lan"
  hosts: srv201.lan
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

#### SRV202.LAN ####
- name: Run on "srv202.lan"
  hosts: srv202.lan
  gather_facts: true
  become: true

  vars_files:
    - group_vars/secrets.yml

  roles:

    - role: nfs
      tags:
        - nfs
