---
- name: Ansible Variable Example Playbook
  hosts: pi_servers
  gather_facts: true

  
  tasks:

     # Accessing the list
    - name: Run Commands
      debug:
        msg: "{{ ansible_play_hosts / ansible_all_ipv4_addresses | list }}"
      loop: '{{ result.stdout | from_yaml_all | list }}'
      run_once: yes
 