---
- name: Fetch Mannual bash install of Crowdsec
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh  | sudo bash

- name: Update apt and install Crowdsec and Prometheus
  apt: 
    update_cache: yes 
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
      #- prometheus
    state: present

- name: Crowdsec cscli completion
  ansible.builtin.shell: cscli completion bash | sudo tee /etc/bash_completion.d/cscli

- name: cscli hub update
  command:
    cmd: cscli hub update
  changed_when: false
    
- name: Install the necessary collections
  command:
    cmd: "sudo cscli collections install crowdsecurity/{{ item }}"
  with_items:
    - nginx
    - sshd
    - linux
    - iptables
  register: collections_install_result
  changed_when: "'overwrite' not in collections_install_result.stderr"

- name: Install the necessary scenarios
  command:
    cmd: "sudo cscli scenarios install crowdsecurity/{{ item }}"
  with_items:
    - apache_log4j2_cve-2021-44228
    - http-cve-2021-42013
  register: scenarios_install_result
  changed_when: "'overwrite' not in scenarios_install_result.stderr"

- name: Install the necessary parsers
  command:
    cmd: "sudo cscli parsers install crowdsecurity/{{ item }}"
  with_items:
    - docker-logs
  register: parsers_install_result
  changed_when: "'overwrite' not in parsers_install_result.stderr"

- name: Enable the Prometheus endpoint
  lineinfile:
    path: "/etc/crowdsec/config.yaml"
    line: "  enabled: true"
    search_string: "enabled: false"
    insertafter: "^prometeus:.*$"
  notify:
    - Restart prometheus
    - Restart crowdsec

- name: Increase ban time
  replace:
    path: "/etc/crowdsec/profiles.yaml"
    regexp: 'duration: [0-9]h'
    replace: 'duration: 999h'
  notify:
    - Restart crowdsec

- name: Start and enable Crowdsec services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
      - crowdsec
      - crowdsec-firewall-bouncer
      - prometheus
