enable_os_update: true
enable_extra_packages: true
enable_extra_packages_nettools: false
enable_cockpit: false
enable_auditd: false
enable_rkhunter: true
enable_lynis: false

#NFS
nfsclient_local_folder: "/opt/share/docker"
nfsclient_nfs_connect: "192.168.30.103:/mnt/share/docker" 

docker_dir: /opt/share/docker/docker01_lan

## Firewall 
enable_ufw: true
enable_ufw_deny_out: true
resetufw: false

open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'tcp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }
  - { src: any, dest: any, port: '7844', proto: any, direction: out, comment: 'Cloudflaretunnels' }

  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }