enable_os_update: true
enable_extra_packages: true
enable_extra_packages_nettools: false
enable_cockpit: false
enable_auditd: true
enable_rkhunter: true
enable_lynis: true

## Firewall 
enable_ufw: true
resetufw: false

# Outgoing
enable_ufw_deny_out: true

# Default ports Outgoing
enable_out_ssh_22: true
enable_out_dns_53: true
enable_out_web_80: true
enable_out_ntp_123: true
enable_out_web_443: true

# Default ports incomming
enable_dns53: false
enable_web80: false
enable_web443: false

# System ports incomming
enable_nfs: true
enable_docker: true
enable_crowdsec: false
enable_portainer: false
enable_littlelink: true
enable_uptimekuma: false
enable_watchtower: false
enable_dockge: false 


local_lan_ufw:
  - 192.168.30.0/24   # Vlan homlab
  - 192.168.10.0/24   # Vlan secure
  - fd00::/8          # # Default Lan Ipv6

nfsclient_local_folder: "/opt/share/docker"
nfsclient_nfs_connect: "192.168.30.103:/mnt/share/docker" 

docker_dir: /opt/share/docker/docker01_lan
