enable_os_update: true
enable_extra_packages: true
enable_extra_packages_nettools: false
enable_cockpit: false
enable_auditd: false
enable_rkhunter: false
enable_lynis: false

## Firewall 
enable_ufw: true
enable_ufw_deny_out: true
resetufw: false

open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'tcp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: '192.168.10.0/24', dest: any, port: '80', proto: 'tcp', direction: in, comment: 'HTTP # Secure Vlan' }
  - { src: '192.168.10.0/24', dest: any, port: '22', proto: 'tcp', direction: in, comment: 'SSH # Secure Vlan' }

  - { src: '192.168.3.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # VPN VLAN' }
  - { src: '192.168.10.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Secure Vlan' }
  - { src: '192.168.20.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Mart Vlan' }
  - { src: '192.168.30.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # HomeLab Vlan' }
  - { src: '192.168.31.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # HomeLab DMZ Vlan' }
  - { src: '192.168.99.0/24', dest: any, port: '53', proto: any, direction: in, comment: 'DNS # Insecure Vlan' }
