- name: Create an internal macvlan network
  docker_network:
    name: swag_internal_macvlan
    driver: macvlan
    driver_options:
      parent: enp2s0.4
    ipam_config:
      - subnet: "{{ swag_network }}"
        gateway: "{{ swag_gateway }}"

- name: Create a public macvlan network
  docker_network:
    name: swag_public_macvlan
    driver: macvlan
    driver_options:
      parent: enp5s0
    ipam_config:
      - subnet: "{{ dmz_network }}"
        gateway: "{{ dmz_gateway }}"
