---
- name: Generate 'deploy' SSH key.
  hosts: localhost
  connection: local
  vars:
    ssh_key_filename: deploy

  tasks:
    - name: Generate SSH key "{{ ssh_key_filename }}"
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{ ssh_key_filename }}"
        type: ed25519
        state: present
        force: false
        regenerate: full_idempotence

- name: Generate 'sema_deploy' SSH key.
  hosts: localhost
  connection: local
  vars:
    ssh_key_filename: sema_deploy

  tasks:
    - name: Generate SSH key "{{ ssh_key_filename }}"
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{ ssh_key_filename }}"
        type: ed25519
        state: present
        force: false
        regenerate: full_idempotence

