---
- name: Run on all DEV_SERVERS
  hosts: dev
  gather_facts: false
  become: true

  roles:
    - role: system
    - role: geerlingguy.ntp
    - role: geerlingguy.security

###
- name: Run on "dev01.dev"
  hosts: dev01.dev
  gather_facts: true
  become: true

  roles:
    - role: ufw
      tags: ufw

  tasks:
    - name: Essential-debian | Install extra packages
      ansible.builtin.package:
        name: "{{ extra_packages }}"
        state: present

    - name: Check if a reboot is required on Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: ubuntu_reboot_required

    - name: Reboot Debian/Ubuntu if required
      when: ubuntu_reboot_required.stat.exists | default(false)
      ansible.builtin.reboot:
        reboot_timeout: 600
