---
- name: Localhost playbooks inventory to hostfile ans ~/.ssh/config
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      become: true
      ansible.builtin.blockinfile:
        marker: "### -- PROD -- ANSIBLE MANAGED BLOCK {mark}###"
        append_newline: true
        path: /etc/hosts
        block: |
          {% for host in groups['prod_servers'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}
          {% for host in groups['prod_proxmox_servers'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}

    - name: Add Ansible inventory mappings to ~/.ssh/config
      become: false
      ansible.builtin.blockinfile:
        marker: "### -- PROD -- ANSIBLE MANAGED BLOCK {mark}###"
        append_newline: true
        path: /home/rolf/.ssh/config
        block: |
            {% for host in groups['prod_servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['prod_proxmox_servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User root
                Port 22
                IdentityFile ~/.ssh/deploy_hw
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}

