---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: all

  vars_files:
    - ../group_vars/secrets.yml

  tasks:
    # - name: Get services facts
    #   ansible.builtin.service_facts:

    # - name: Get services facts of crowdsec.service
    #   ansible.builtin.debug:
    #     var: ansible_facts.services['crowdsec.service']
    #   when:
    #     - ansible.builtin.ansible_facts.services['crowdsec.service']['status'] == 'enabled'
    #     - ansible.builtin.ansible_facts.services['crowdsec.service']['state'] == 'running'

    # - name: Get services facts of crowdsec-firewall-bouncer.service
    #   ansible.builtin.debug:
    #     var: ansible_facts.services['crowdsec-firewall-bouncer.service']
    #   when:
    #     - ansible.builtin.ansible_facts.services['crowdsec-firewall-bouncer.service']['status'] == 'enabled'
    #     - ansible.builtin.ansible_facts.services['crowdsec-firewall-bouncer.service']['state'] == 'running'

    - name: Show password from vault
      ansible.builtin.debug:
        var: username_sec

    - name: Show password from vault
      ansible.builtin.debug:
        var: userpassword_sec


# tasks:
    # - debug: var=inventory_hostname
    # - debug: var=ansible_hostname
    # - debug: var=ansible_distribution
    # - debug: var=ansible_distribution_file_variety
    # - debug: var=ansible_os_family
    # - debug: var=ansible_distribution_major_version
    # # - debug: var=ansible_dns
    # - debug: var=ansible_domain
    # - debug: var=ansible_eth0
    # - debug: var=ansible_all_ipv4_addresses
    # - debug: var=ansible_default_ipv4
    # - debug: var=ansible_fqdn
    # - debug: var=ansible_selinux
    # - debug: var=ansible_ssh_host_key_ecdsa_public
    # - debug: var=ansible_ssh_host_key_ed25519_public
    # - debug: var=ansible_ssh_host_key_rsa_public
    # - debug: var=ansible_date_time
    # - debug: var=ansible_date_time.iso8601
    # - debug: var=ansible_distribution
    # - debug: var=ansible_distribution_release
    # - debug: var=ansible_distribution_version
    # - debug: var=docker_container_info
    # - debug: var=ansible_processor_cores

    # #- debug: var=hostvars
