---
- name: Localhost playbooks inventory to hostfile ans ~/.ssh/config
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      become: true
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['prod_servers'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}
          {% for host in groups['test_servers'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}
          {% for host in groups['windows'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}
          {% for host in groups['pi4_hw'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}
          {% for host in groups['pve_hw'] %}
          {{ hostvars[host].ansible_host }}   {{ host }}
          {% endfor %}

    - name: Add Ansible inventory mappings to ~/.ssh/config
      become: false
      ansible.builtin.blockinfile:
        path: /home/rolf/.ssh/config
        block: |
            {% for host in groups['pi4_hw'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User {{ hostvars[host].ansible_user }}
                Port 22
                IdentityFile {{ hostvars[host].ansible_ssh_private_key_file }}
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['pve_hw'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User {{ hostvars[host].ansible_user }}
                Port 22
                IdentityFile {{ hostvars[host].ansible_ssh_private_key_file }}
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['prod_servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['test_servers'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
            {% for host in groups['windows'] %}
            host {{ host }}
                HostName {{ hostvars[host].ansible_host }}
                User deploy
                Port 22
                IdentityFile ~/.ssh/deploy
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null

            {% endfor %}
