---

- name: Network Getting Started First Playbook
  gather_facts: true
  become: true
  hosts: all

  vars_files:
    - ../group_vars/secrets.yml

  tasks:
    - name: Get services facts
      ansible.builtin.service_facts:

    - name: Loop over all services and print name
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ ansible_facts.services }}"
      when:
        - ansible_facts.services[item].state == 'running'


    # - name: Gather facts on listening ports
    #   community.general.listen_ports_facts:

    # - name: List all TCP ports
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts.tcp_listen }}"

    # - name: List all UDP ports
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts.udp_listen }}"
# tasks:
    # - debug: var=inventory_hostname
    # - debug: var=ansible_hostname
    # - debug: var=ansible_distribution
    # - debug: var=ansible_distribution_file_variety
    # - debug: var=ansible_os_family
    # - debug: var=ansible_distribution_major_version
    # # - debug: var=ansible_dns
    # - debug: var=ansible_domain
    # - debug: var=ansible_eth0
    # - debug: var=ansible_all_ipv4_addresses
    # - debug: var=ansible_default_ipv4
    # - debug: var=ansible_fqdn
    # - debug: var=ansible_selinux
    # - debug: var=ansible_ssh_host_key_ecdsa_public
    # - debug: var=ansible_ssh_host_key_ed25519_public
    # - debug: var=ansible_ssh_host_key_rsa_public
    # - debug: var=ansible_date_time
    # - debug: var=ansible_date_time.iso8601
    # - debug: var=ansible_distribution
    # - debug: var=ansible_distribution_release
    # - debug: var=ansible_distribution_version
    # - debug: var=docker_container_info
    # - debug: var=ansible_processor_cores

    # #- debug: var=hostvars
