---

- name: Run on all PROD_SERVERS
  hosts: prod:!hardware:!dev:!test
  gather_facts: false
  become: false

- name: Include dns servers setup/configuration
  ansible.builtin.import_playbook: prod_dns_servers.yml
  when: group_names | select('regex', '^.*(prod_dns_servers)$') | list | count > 0

- name: Include DMZ / external servers setup/configuration
  ansible.builtin.import_playbook: prod_dmz_servers.yml
  when: group_names | select('regex', '^.*(prod_dmz_servers)$') | list | count > 0

- name: Include Mail servers and relays setup/configuration
  ansible.builtin.import_playbook: prod_mail_servers.yml
  when: group_names | select('regex', '^.*(prod_mail_servers)$') | list | count > 0

- name: Include proxy servers servers setup/configuration
  ansible.builtin.import_playbook: prod_proxy_servers.yml
  when: group_names | select('regex', '^.*(prod_proxy_servers)$') | list | count > 0

- name: Include Source controle/git servers setup/configuration
  ansible.builtin.import_playbook: prod_source_servers.yml
  when: group_names | select('regex', '^.*(prod_source_servers)$') | list | count > 0

- name: Include docker servers setup/configuration
  ansible.builtin.import_playbook: prod_docker_servers.yml
  when: group_names | select('regex', '^.*(prod_docker_servers)$') | list | count > 0

- name: Include automation servers setup/configuration
  ansible.builtin.import_playbook: prod_auto_servers.yml
  when: group_names | select('regex', '^.*(prod_auto_servers)$') | list | count > 0
