---

- name: Run on "mail servers/relays"
  hosts: prod_mail_servers:!hardware
  gather_facts: false
  become: true

  roles:
    - role: system
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp
    - role: ufw
      tags: ufw
    - role: postfix
      tags: postfix
