---

- name: Run on "prod_docker_servers"
  hosts: docker02.lan:!hardware
  gather_facts: true
  become: true

  roles:
    - role: system
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp
    - role: geerlingguy.pip
      tags: containers
    - role: geerlingguy.docker
      tags: containers
    - role: ufw
      tags: ufw

- name: Run on "prod_docker_servers"
  hosts: docker02.lan:!hardware
  gather_facts: true
  become: true
  become_user: deploy

  roles:
    - role: ironicbadger.docker_compose_generator
      tags: compose

