---

- name: Run on all PROD_SERVERS
  hosts: prod:!hardware:!dev:!test
  gather_facts: false
  become: false

- name: Include DNS servers setup/configuration
  ansible.builtin.import_playbook: prod_dns_servers.yml
  when: group_names | select('regex', '^.*(prod_dns_servers)$') | list | count > 0

- name: Include DMZ / external servers setup/configuration
  ansible.builtin.import_playbook: prod_dmz_servers.yml
  when: group_names | select('regex', '^.*(prod_dmz_servers)$') | list | count > 0

- name: Include Mail servers and relays setup/configuration
  ansible.builtin.import_playbook: prod_mail_servers.yml
  when: group_names | select('regex', '^.*(prod_mail_servers)$') | list | count > 0

- name: Include PROXY servers servers setup/configuration
  ansible.builtin.import_playbook: prod_proxy_servers.yml
  when: group_names | select('regex', '^.*(prod_proxy_servers)$') | list | count > 0

- name: Include Source controle/git servers setup/configuration
  ansible.builtin.import_playbook: prod_source_servers.yml
  when: group_names | select('regex', '^.*(prod_source_servers)$') | list | count > 0

- name: Include Docker servers setup/configuration
  ansible.builtin.import_playbook: prod_docker_servers.yml
  when: group_names | select('regex', '^.*(prod_docker_servers)$') | list | count > 0

- name: Include Automation servers setup/configuration
  ansible.builtin.import_playbook: prod_auto_servers.yml
  when: group_names | select('regex', '^.*(prod_auto_servers)$') | list | count > 0

- name: Include First boot setup/configuration
  ansible.builtin.import_playbook: prod_servers_first.yml
  when: group_names | select('regex', '^.*(boot)$') | list | count > 0
