---
###
- name: Run on "prod_dmz_servers"
  hosts: prod_dmz_servers:!hardware
  gather_facts: true
  become: true

  roles:
    - role: system
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp
    - role: ufw
      tags: ufw

# manual installed tailscale
# manual install Cloudflare tunnels
# curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
# sudo systemctl restart cloudflared.service
