---
### tested via just ansi_hardware on 04-01-2025
### this was the test parameters
###    ansible-playbook playbooks/prod_dns_servers.yml -i inventories/prod.ini --vault-password-file ~/.vault_pass --tags piholeupdate,os_update  --extra-vars "enable_pihole_update=true, enable_os_update=true"  --limit="prod_dns_servers"
### Should beable to run via automation (semaphore)

- name: Run on "prod_dns_servers"
  hosts: prod_dns_servers:!hardware
  gather_facts: true
  become: true

  roles:
    - role: system
    - role: geerlingguy.ntp
      tags: ntp
    - role: geerlingguy.security
      tags: security
    - role: ufw
      tags: ufw

  tasks:

    - name: Add ssh authorized_keys to users
      ansible.posix.authorized_key:
        user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32306365653061653732623066353232363763363362663036303336313563663331393431356563
          6162313465373734373862623236393636336331616665370a373662333138353236396437616430
          39303832333330396234653333366331396366666164643761386262663934313866636364633238
          6330363463306339380a353839656537373530653139303063363436303631313439653932353163
          3034
        key: "{{ pi_sync_key }}"
        exclusive: false

    - name: Update PiHole with bash
      register: ouputup
      changed_when: ouputup.rc != 0
      ansible.builtin.command: "/usr/local/bin/pihole -up"
      when: enable_pihole_update
      tags: piholeupdate
    - name: Update PiHole Gravaty with bash
      register: ouputg
      changed_when: ouputg.rc != 0
      ansible.builtin.command: "/usr/local/bin/pihole -g"
      when: enable_pihole_update
      tags: piholeupdate
    - name: Restart PiHole DNS with bash
      register: ouputdns
      changed_when: ouputdns.rc != 0
      ansible.builtin.command: "/usr/local/bin/pihole restartdns reload"
      when: enable_pihole_update
      tags: piholeupdate
