---

- name: Run on "prod_proxy_servers"
  hosts: prod_proxy_servers:!hardware
  gather_facts: true
  become: true

  roles:
    - role: system
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp
    - role: ufw
      tags: ufw
    - role: caddy
      tags:
        - caddy
        - caddyfile
