---
### Should NOT run via automation (semaphore) since HW that automation is running on can restart.
### automation server should be moved to other HW.

- name: Run on "hardware"
  hosts: hardware
  gather_facts: true
  become: true

  tasks:

    - name: Upgrade apt packages (Debian and Ubuntu)
      when: enable_os_update | d(false) | bool
      block:
        - name: Upgrade apt packages (Debian and Ubuntu)
          ansible.builtin.apt:
            force_apt_get: true
            upgrade: true
            autoremove: true
            update_cache: true
            cache_valid_time: 3600
          when: ansible_os_family | lower == "debian"
          changed_when: false
        - name: Check if a reboot is needed on all servers
          register: reboot_required_file
          ansible.builtin.stat:
            path: /var/run/reboot-required
        - name: Reboot the box if kernel updated
          ansible.builtin.reboot:
            msg: "Reboot initiated by Ansible for kernel updates"
          when: reboot_required_file.stat.exists

- name: Run on "proxmox_ve_servers"
  hosts: proxmox_ve_servers
  gather_facts: true
  become: true

  roles:
    - role: proxmox_nag_removal

- name: Run on "proxmox_backup_servers"
  hosts: proxmox_backup_servers
  gather_facts: true
  become: true

  roles:
    - role: proxmox_pbs_nag_removal
