---
###
- name: Run on "caddy01.lan"
  hosts: caddy01.lan
  gather_facts: true
  become: true

  roles:
    - role: ufw
      tags: ufw
    - role: caddy
      tags:
        - caddy
        - caddyfile
