---
#
# Tasks and roles for all hosts
#


###
- name: Run on "caddy01.lan"
  hosts: caddy01.lan
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: ufw
      tags: ufw
    - role: caddy
      tags:
        - caddy
        - caddyfile
