---
###
- name: Run on "cloud01.lan"
  hosts: cloud01.lan
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: ufw
      tags: ufw
# manual installed tailscale
# manual install Cloudflare tunnels
# curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
# sudo systemctl restart cloudflared.service
