---
#
# Tasks and roles for all hosts
#

- name: Run on all ORA servers
  hosts: ora01.test
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  tasks:
    - name: Install packages
      tags: packages
      ansible.builtin.dnf:
        name:
          - jq
          - git
        state: present

  roles:
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp
    - role: geerlingguy.docker
      tags: containers
