---

- name: Run on all PROD Hardware Servers
  hosts: pve.lan:pve1.lan
  become: true

  pre_tasks:
    - name: Upgrade apt packages (Debian and Ubuntu)
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family | lower == "debian"
        - enable_os_update
      changed_when: false

###
- name: Run on "ProxMox Servers"
  hosts: pve.lan
  gather_facts: false
  become: true

  roles:
    - role: ironicbadger.proxmox_nag_removal
