---

- name: Run on "proxmox_ve_servers"
  hosts: proxmox_ve_servers
  gather_facts: true
  become: true

  roles:
    - role: proxmox_nag_removal

- name: Run on "proxmox_backup_servers"
  hosts: proxmox_backup_servers
  gather_facts: true
  become: true

  roles:
    - role: proxmox_pbs_nag_removal
