---
- name: Run on all TEST_SERVERS
  hosts: test_servers
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: system
      tags: system
    - role: geerlingguy.security
      tags: security
    - role: geerlingguy.ntp
      tags: ntp


- name: Run on "dev01.test"
  hosts: dev01.test
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: geerlingguy.pip
      tags: containers
    - role: geerlingguy.docker
      tags: containers
    - role: ufw
      tags: ufw

  tasks:
    - name: Essential-debian | Install extra packages
      ansible.builtin.package:
        name: "{{ extra_packages }}"
        state: present


- name: Run on "srv01.test"
  hosts: srv01.lan
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: geerlingguy.pip
      tags: containers
    - role: geerlingguy.docker
      tags: containers
    - role: ufw
      tags: ufw
    - role: littlelink
      tags:
        - containers
        - littlelink


- name: Run on "srv02.test"
  hosts: srv02.lan
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: geerlingguy.pip
      tags: containers
    - role: geerlingguy.docker
      tags: containers
    - role: ufw
      tags: ufw


- name: Run on "srv03.test"
  hosts: srv03.lan
  gather_facts: true
  become: true

  vars_files: ../group_vars/secrets.yml

  roles:
    - role: geerlingguy.pip
      tags: containers
    - role: geerlingguy.docker
      tags: containers
    - role: ufw
      tags: ufw
