---
username: deploy

# Used in Geerlingguy.ntp
ntp_servers:
  - 0.dk.pool.ntp.org
  - 1.dk.pool.ntp.org
  - 2.dk.pool.ntp.org
  - 3.dk.pool.ntp.org

timezone: Europe/Copenhagen
ntp_tinker_panic: true
ntp_manage_config: true
ntp_timezone: "{{ timezone }}"

# Used in geerlingguy.security
security_sudoers_passwordless: [ "{{ username }}" ]
security_fail2ban_enabled: false

# Used in geerlingguy.pip
pip_package: python3-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
pip_install_packages:
      - name: docker
      - name: docker-compose

# Used in geerlingguy.docker
docker_daemon_options: {"iptables": false}
docker_users:
  - "{{ username }}"

docker_dir: /opt/docker/data

extra_packages: []
extra_packages_nettools: []
