# Just for testing in homelab
# ansible-vault decrypt group_vars/secrets.yml to use in prod and sync with git
username_sec: deploy 
userpassword_sec: "$y$j9T$NY84hjha6yxHt3IwsEJoA/$/CUGjfbB6tPhV.81U6HyJdCbOvvQktnWwzPNviwp8H0"
ssh_public_key_sec: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG5iPUMbwcXyBjEp3rJA/d7Qv4HRo83BXo5az0H74kzj"