enable_os_update: true
enable_extra_packages: true
enable_extra_packages_tui: true
enable_extra_packages_desktop: true
enable_extra_packages_nettools: true

desktop: true
flatpak: true
starship: true
visualstudio: true
dotfiles: true
tmux: true
vpn: true
fonts: true
eza: true
tldr: true

extra_packages: 
  - curl
  - wget
  - git
  - nano
  - python3
  - python3-pip
  - apt-transport-https
  - ca-certificates

extra_packages_tui: 
  - jq
  - htop
  - unzip
  - plocate
  - neovim
  - ripgrep
  - fd-find
  - fzf
  - glances
  - bat

extra_packages_desktop: 
  - ubuntu-desktop-minimal
  - nautilus-admin
  - filezilla
  - libreoffice
  - clamtk

## Firewall 
enable_ufw: true
enable_ufw_deny_out: true

open_ports:
  - { src: any, dest: any, port: '22', proto: 'tcp', direction: out, comment: 'SSH' }
  - { src: any, dest: any, port: '53', proto: any, direction: out, comment: 'DNS' }
  - { src: any, dest: any, port: '123', proto: 'udp', direction: out, comment: 'NTP' }
  - { src: any, dest: any, port: '80', proto: 'tcp', direction: out, comment: 'http' }
  - { src: any, dest: any, port: '443', proto: 'tcp', direction: out, comment: 'https' }

  - { src: 'any', dest: '', port: '22', proto: 'tcp', direction: in, comment: 'SSH # KVM / vagrant on localhost' }

  - { src: '192.168.56.0/24', dest: '', port: '80', proto: 'tcp', direction: in, comment: 'http' } #HTTP
  - { src: '192.168.56.0/24', dest: '', port: '443', proto: 'tcp', direction: in, comment: 'https' } #HTTPS
  - { src: '192.168.56.0/24', dest: '', port: '3389', proto: 'tcp', direction: in, comment: 'RDP' } #HTTPS


