---
- include_tasks: clean-up.yml

- include_tasks: install.yml

- name: Configure admin user password
  uri:
    url: "{{ portainer_endpoint }}/users/admin/init"
    method: POST
    return_content: true
    body_format: json
    body: '{ "Username":"{{ admin_user }}", "Password":"{{ admin_password }}"}'
    status_code: 200, 409
  when: admin_user and admin_password is defined

- name: Generate authentication token
  uri:
    url: "{{ portainer_endpoint }}/auth"
    method: POST
    return_content: true
    body_format: json
    body: '{"Username": "{{ admin_user }}", "Password": "{{ admin_password }}"}'
  register: auth_token
  when: admin_user and admin_password is defined

- name: Define Endpoint
  uri:
    url: "{{ portainer_endpoint }}/endpoints"
    method: POST
    return_content: true
    body_format: form-multipart
    headers:
      Authorization: Bearer {{ (auth_token.content|from_json).jwt }}
    body:
      EndpointCreationType: "1"
      Name: "{{ endpoint_name }}"
      PublicURL: "{{ host_ip }}"
  when:
    - remove_existing_container
    - remove_persistent_data

